WhiteCard.create([
  {text: "Goats eating coins."},
  {text: "Inappropriate yelling."},
  {text: "The plot of a Michael Bay movie."},
  {text: "The Red Menace."},
  {text: "Vehicular homicide."},
  {text: "A caress of the inner thigh"},
  {text: "Filling Sean Hannity with helium and watching him float away."},
  {text: "The homosexual lifestyle."},
  {text: "Swag."},
  {text: "A Fleshlight."},
  {text: "Bio-engineered assault turtles with acid breath."},
  {text: "Court-ordered rehab."},
  {text: "Hip hop jewels"},
  {text: "Joe Biden."},
  {text: "Magnets."},
  {text: "Miley Cyrus at 55."},
  {text: "Our first chimpanzee President."},
  {text: "The cool, refreshing taste of Pepsi®."},
  {text: "The morbidly obese."},
  {text: "The pirate’s life."},
  {text: "The wrath of Vladimir Putin."},
  {text: "This year’s mass shooting."},
  {text: "White-man scalps."},
  {text: "(A picture of Sean Connery from the movie Zardoz)"},
  {text: "Masturbating Yoda’s leathery turtle-penis."},
  {text: "A misty room full of glistening egg sacs."},
  {text: "Going too far with science and bad things happening."},
  {text: "Three boobs."},
  {text: "An alternate history where Hitler was gay but he still killed all those people."},
  {text: "A hazmat suit full of farts."},
  {text: "A protagonist with no qualities."},
  {text: "Darmok and Jalad at Tanagra."},
  {text: "Cheerful blowjob robots."},
  {text: "That girl from the Hungry Games."},
  {text: "Cosmic bowling."},
  {text: "The ending of Lost."},
  {text: "Trimming the poop out of Chewbacca’s butt hair."},
  {text: "A planet-devouring space worm named Rachel."},
  {text: "How great of a movie Men in Black was."},
  {text: "Nine seasons of sexual tension with David Duchovny."},
  {text: "Frantically writing equations on a chalkboard."},
  {text: "Vulcan sex-madness."},
  {text: "Funkified aliens from the planet Groovius."},
  {text: "The dystopia we’re living in right now."},
  {text: "Laying thousands of eggs in a man’s colon."},
  {text: "Beep beep boop beep boop."},
  {text: "Mild amusement"},
  {text: "Casual dismissiveness."},
  {text: "A gnawing sense of dread."},
  {text: "Rage."},
  {text: "Desperately hurling insults at Donald Trump as he absorbs them into his rapidly expanding body."},
  {text: "Trying to wake up from this nightmare."},
  {text: "Finding out democracy might not be such a great idea."},
  {text: "President Donald Trump."},
  {text: "Bringing millions of dangerous, low-paying manufacturing jobs back to America."},
  {text: "Whipping lower-class white men into a xenophobic frenzy."},
  {text: "Making Islam illegal."},
  {text: "The purging of the disloyal."},
  {text: "World Wars 3 through 5."},
  {text: "Nuclear winter."},
  {text: "Roaming through a wasteland of windblown trash and deserted highways."},
  {text: "A black-alley abortion from a Mexican cyborg doctor."},
  {text: "A father and son fighting each other over the last scrap of bread."},
  {text: "Burying my only son."},
  {text: "Extra rations for my litter girl."},
  {text: "Drinking urine to survive."},
  {text: "Trying to remember what music was."},
  {text: "A legitimate reason to commit suicide."},
  {text: "A 55-gallon drum of lube."},
  {text: "A bigger, blacker dick."},
  {text: "A Burmese tiger pit."},
  {text: "A dollop of sour cream."},
  {text: "A fortuitous turnip harvest."},
  {text: "A magic hippie love cloud."},
  {text: "A man in yoga pants with a ponytail and feather earrings."},
  {text: "A piñata full of scorpions"},
  {text: "A sad fat dragon with no friends."},
  {text: "A slightly shittier parallel universe."},
  {text: "A sofa that says “I have style, but I like to be comfortable.”"},
  {text: "A soulful rendition of “Ol’ Man River.”"},
  {text: "A squadron of moles wearing aviator goggles."},
  {text: "A sweaty, panting leather daddy."},
  {text: "A sweet spaceship."},
  {text: "All of this blood."},
  {text: "An army of skeletons."},
  {text: "An ether-soaked rag."},
  {text: "An unhinged ferris wheel rolling toward the sea."},
  {text: "Another shot of morphine."},
  {text: "Basic human decency."},
  {text: "Beefin’ over turf."},
  {text: "Being awesome at sex."},
  {text: "Boris the Soviet Love Hammer."},
  {text: "Bullshit."},
  {text: "Catastrophic urethral trauma."},
  {text: "Crushing Mr. Peanut’s brittle body."},
  {text: "Daddy’s belt"},
  {text: "Death by Steven Seagal."},
  {text: "Dennis the Menace."},
  {text: "Dining with cardboard cutouts of the cast of “Friends.”"},
  {text: "Double penetration."},
  {text: "Existing."},
  {text: "Fetal alcohol syndrome."},
  {text: "Finding Waldo."},
  {text: "Fuck Mountain."},
  {text: "Getting hilariously gang-banged by the Blue Man Group."},
  {text: "Grandpa’s ashes."},
  {text: "Graphic violence, adult language, and some sexual content."},
  {text: "Hillary Clinton’s death stare."},
  {text: "Intimacy problems."},
  {text: "Jeff Goldblum."},
  {text: "Living in a trashcan."},
  {text: "Loki, the trickster god."},
  {text: "Making a friend."},
  {text: "Maximal insertion."},
  {text: "Me."},
  {text: "Mild autism."},
  {text: "Mooing."},
  {text: "My first kill."},
  {text: "Nunchuck moves."},
  {text: "Oncoming traffic."},
  {text: "One Ring to rule them all."},
  {text: "Power"},
  {text: "Pretty Pretty Princess Dress-Up Board Game®."},
  {text: "Pumping out a baby every nine months."},
  {text: "Rising from the grave."},
  {text: "Scrotal frostbite."},
  {text: "Some really fucked-up shit."},
  {text: "Special musical guest, Cher."},
  {text: "Spring break!"},
  {text: "Subduing a grizzly bear and making her your wife."},
  {text: "Survivor’s guilt."},
  {text: "Swiftly achieving orgasm."},
  {text: "Taking a man’s eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes."},
  {text: "The black Power Ranger"},
  {text: "The corporations."},
  {text: "The day the birds attacked."},
  {text: "The Google."},
  {text: "The grey nutrient broth that sustains Mitt Romney."},
  {text: "The human body."},
  {text: "The mere concept of Applebee’s®."},
  {text: "The mixing of the races."},
  {text: "The new Radiohead album."},
  {text: "Tiny nipples."},
  {text: "Tongue."},
  {text: "Upgrading homeless people to mobile hotspots."},
  {text: "Weapons-grade plutonium."},
  {text: "Wearing an octopus for a hat."},
  {text: "Whining like a little bitch."},
  {text: "Whipping a disobedient slave."},
  {text: "That ass."},
  {text: "Nothing."},
  {text: "Shutting the fuck up."},
  {text: "The primal, ball-slapping sex your parents are having right now."},
  {text: "A cat video so cute that your eyes roll back and your spine slides out of your anus."},
  {text: "Cock."},
  {text: "A cop who is also a dog."},
  {text: "Dying alone and in pain."},
  {text: "Gay aliens."},
  {text: "The way white people is."},
  {text: "Reverse cowgirl."},
  {text: "The Quesadilla Explosion Salad from Chili’s."},
  {text: "Actually getting shot, for real."},
  {text: "Not having sex."},
  {text: "Vietnam flashbacks."},
  {text: "Running naked through a mall, pissing and shitting everywhere."},
  {text: "Warm, velvety muppet sex."},
  {text: "Self-flagellation."},
  {text: "The systematic destruction of an entire people and their way of life."},
  {text: "Samuel L. Jackson."},
  {text: "A boo-boo."},
  {text: "Going around punching people."},
  {text: "The entire Internet."},
  {text: "Some kind of bird-man."},
  {text: "Chugging a lava lamp."},
  {text: "Having sex on top of a pizza."},
  {text: "Indescribable loneliness."},
  {text: "An ass disaster."},
  {text: "All my friends dying."},
  {text: "Putting an entire peanut buter and jelly sandwich into the VCR."},
  {text: "Spending lots of money."},
  {text: "Some douche with an acoustic guitar."},
  {text: "Flying robots that kill people."},
  {text: "A greased-up Matthew McConaughey."},
  {text: "An unstoppable wave of fire ants."},
  {text: "Not contributing to society in any meaningful way."},
  {text: "An all-midget production of Shakespeare’s Richard III."},
  {text: "Screaming like a maniac."},
  {text: "The moist, demanding chasm of his mouth."},
  {text: "Filling every orifice with butterscotch pudding."},
  {text: "Unlimited soup, salad, and breadsticks."},
  {text: "Crying into the pages of Sylvia Plath."},
  {text: "Velcro."},
  {text: "A PowerPoint presentation."},
  {text: "A surprising amount of hair."},
  {text: "Eating Tom Selleck’s mustache to gain his powers."},
  {text: "Roland the Farter, flatulist to the king."},
  {text: "A pile of squirming bodies."},
  {text: "Buying the right pants to be cool."},
  {text: "Blood farts."},
  {text: "Three months in the hole."},
  {text: "A botched circumcision."},
  {text: "The Land of Chocolate."},
  {text: "Slapping a racist old lady."},
  {text: "A lamprey swimming up the toilet and latching onto your taint."},
  {text: "Jumping out at people."},
  {text: "A black male in his early 20s, last seen wearing a hoodie."},
  {text: "Mufasa’s death scene."},
  {text: "Bill Clinton, naked on a bearskin rug with a saxophone."},
  {text: "Demonic possession."},
  {text: "The Harlem Globetrotters."},
  {text: "Vomiting mid-blowjob."},
  {text: "My manservant, Claude."},
  {text: "Having shotguns for legs."},
  {text: "Letting everyone down."},
  {text: "A spontaneous conga line."},
  {text: "A vagina that leads to another dimension."},
  {text: "Disco fever."},
  {text: "Getting your dick stuck in a Chinese finger trap with another dick."},
  {text: "Fisting."},
  {text: "The thin veneer of situational causality that underlies porn."},
  {text: "Girls that always be textin’."},
  {text: "Blowing some dudes in an alley."},
  {text: "Drinking ten 5-hour ENERGYs to get fifty continuous hours of energy."},
  {text: "Sneezing, farting, and coming at the same time."},
  {text: "A bunch of idiots playing a card game instead of interacting like normal humans."},
  {text: "A sex goblin with a carnival penis."},
  {text: "Lots and lots of abortions."},
  {text: "Injecting speed into one arm and horse tranquilizer into the other."},
  {text: "Sharks with legs."},
  {text: "A sex comet from Neptune that plunges the Earth into eternal sexiness."},
  {text: "How awesome I am."},
  {text: "Smoking crack, for instance."},
  {text: "A dance move that’s just sex."},
  {text: "A hopeless amount of spiders."},
  {text: "Drinking responsibly."},
  {text: "Angelheaded hipsters burning for the ancient heavenly connection to the starry dynamo in the machinery of the night."},
  {text: "Bouncing up and down."},
  {text: "A shiny rock that proves I love you."},
  {text: "Crazy opium eyes."},
  {text: "Moderate-to-severe joint pain."},
  {text: "Finally finishing off the Indians."},
  {text: "Actual mutants with medical conditions and no superpowers."},
  {text: "The complex geopolitical quagmire that is the Middle East."},
  {text: "Neil Diamond’s Greatest Hits."},
  {text: "No clothes on, penis in vagina."},
  {text: "Whispering all sexy."},
  {text: "A horse with no legs."},
  {text: "Depression."},
  {text: "Almost giving money to a homeless person."},
  {text: "Interspecies marriage."},
  {text: "Blackula."},
  {text: "What Jesus would do."},
  {text: "A manhole."},
  {text: "My dad’s dumb fucking face."},
  {text: "A Ugandan warlord."},
  {text: "My worthless son."},
  {text: "A Native American who solves crimes by going into the spirit world."},
  {text: "A kiss on the lips."},
  {text: "A fart."},
  {text: "The peaceful and nonthreatening rise of China."},
  {text: "Snorting coke off a clown’s boner."},
  {text: "Three consecutive seconds of happiness."},
  {text: "Falling into the toilet."},
  {text: "Ass to mouth."},
  {text: "Some sort of Asian."},
  {text: "The size of my penis."},
  {text: "The safe word."},
  {text: "Party Mexicans."},
  {text: "Ambiguous sarcasm."},
  {text: "Jizz."},
  {text: "An interracial handshake."},
  {text: "10 Incredible Facts About the Anus."},
  {text: "The secret formula for ultimate female satisfaction."},
  {text: "Sugar madness."},
  {text: "Calculating every mannerism so as not to suggest homosexuality."},
  {text: "Fucking a corpse back to life."},
  {text: "All the single ladies."},
  {text: "Whatever a McRib is made of."},
  {text: "Africa."},
  {text: "The euphoric rush of strangling a drifter."},
  {text: "Khakis."},
  {text: "A gender identity that can only be conveyed through slam poetry."},
  {text: "Stuffing a child’s face with Fun Dip until he starts having fun."},
  {text: "A for-real lizard that spits blood from its eyes."},
  {text: "The tiniest shred of evidence that God is real."},
  {text: "Prince Ali, fabulous he, Ali Ababwa."},
  {text: "Dem titties."},
  {text: "Exploding pigeons."},
  {text: "My sex dungeon."},
  {text: "Child Protective Services."},
  {text: "Doo-doo."},
  {text: "Sports."},
  {text: "Unquestioning obedience."},
  {text: "Grammar nazis who are also regular Nazis."},
  {text: "40 acres and a mule."},
  {text: "A crazy little thing called love."},
  {text: "A disappointing salad."},
  {text: "A face full of horse cum."},
  {text: "A giant powdery manbaby."},
  {text: "A mouthful of potato salad."},
  {text: "A one-way ticket to Gary, Indiana."},
  {text: "A powered exoskeleton."},
  {text: "A reason not to commit suicide."},
  {text: "A team of lawyers."},
  {text: "A whole new kind of porn."},
  {text: "A zero-risk way to make $2,000 from home."},
  {text: "AIDS monkeys."},
  {text: "All these decorative pillows."},
  {text: "An unforgettable quinceañera."},
  {text: "An uninterrupted history of imperialism and exploitation."},
  {text: "Anal fissures like you wouldn’t believe."},
  {text: "Ancient Athenian boy-fucking."},
  {text: "Backwards knees."},
  {text: "Being nine years old."},
  {text: "Being paralyzed from the neck down."},
  {text: "Being worshiped as the one true God."},
  {text: "Blackface."},
  {text: "Blowjobs for everyone."},
  {text: "Boring Vaginal sex."},
  {text: "Butt stuff."},
  {text: "Changing a person’s mind with logic and facts."},
  {text: "Child support payments."},
  {text: "Cutting off a flamingo’s legs with garden shears."},
  {text: "Daddy’s credit card."},
  {text: "Deez nuts."},
  {text: "Denzel."},
  {text: "Doing the right stuff to her nipples."},
  {text: "Ejaculating live bees and the bees are angry."},
  {text: "Ennui."},
  {text: "Figuring out how to have sex with a dolphin."},
  {text: "Free ice cream, yo."},
  {text: "Genghis Khan’s DNA."},
  {text: "Getting caught by the police and going to jail."},
  {text: "Getting drive-by shot."},
  {text: "Getting eaten alive by Guy Fieri."},
  {text: "Giant sperm from outer space."},
  {text: "Going to a high school reunion on ketamine."},
  {text: "Having been dead a while."},
  {text: "Mom’s new boyfriend."},
  {text: "My boyfriends stupid penis."},
  {text: "My dead son’s baseball glove."},
  {text: "My first period."},
  {text: "Not believing in giraffes."},
  {text: "Oil!"},
  {text: "Out-of-this-world bazongas."},
  {text: "P.F. Chang himself."},
  {text: "Russian super-tuberculosis."},
  {text: "Seeing my village burned and my family slaughtered before my eyes."},
  {text: "Seeing things from Hitler’s perspective."},
  {text: "September 11th, 2001."},
  {text: "Slowly easing down onto a cucumber."},
  {text: "Social justice warriors with flamethrowers of compassion."},
  {text: "Some shit-hot guitar licks."},
  {text: "The Abercrombie & Fitch lifestyle."},
  {text: "The basic suffering that pervades all of existence."},
  {text: "The eight gay warlocks who dictate the rules of fashion."},
  {text: "The ghost of Marlon Brando."},
  {text: "The inability to form meaningful relationships."},
  {text: "The passage of time."},
  {text: "The swim team, all at once."},
  {text: "The tiger that killed my father."},
  {text: "The unbelievable world of mushrooms."},
  {text: "The black half of Barack Obama."},
  {text: "The white half of Barack Obama."},
  {text: "Too much cocaine."},
  {text: "Unrelenting genital punishment."},
  {text: "Vegetarian options."},
  {text: "Wearing glasses and sounding smart."},
  {text: "Western standards of beauty."},
  {text: "Doing the wrong thing."},
  {text: "Carole Baskin."},
  {text: "Joe Exotic."},
  {text: "The tiger that ate Carole Baskin's Husband"},
  {text: "Boris Johnson"},
  {text: "Dominic Raab"},
  {text: "Rishi Sunak"},
  {text: "Michael Gove"},
  {text: "Matt Hancock"},
  {text: "Jeremy Hunt"},
  {text: "Jeremy Corbyn"},
  {text: "Bernie Sanders"},
  {text: "Donald Trump"},
  {text: "Edibles"},
  {text: "PPE"},
  {text: "The STDs that I gave to your mom"},
  {text: "Having a 3 way on Zoom."},
  {text: "A fuck ton of shrooms."},
  {text: "Fresh cat urine."},
  {text: "vaginal flatulence"},
  {text: "pinkeye"},
  {text: "The knights that say Ni."},
  {text: "A woman president."},
  {text: "Dancing carefree in white linen pants."},
  {text: "Drinking Beyonce's DivaCup and becoming immortal."},
  {text: "Masturbating with a Sonicare."},
  {text: "Driving my daughter to her abortion."},
  {text: "Period globs."},
  {text: "Eating three sleeves of Chips Ahoy!"},
  {text: "Feeling lots of feelings."},
  {text: "Destryoying a pair of underwear."},
  {text: "A diverse group of female friends casually discussing the side effects of birth control."},
  {text: "Wringing out a sopping wet maxi pad into Donald Trump's mouth."},
  {text: "Demonic possessions."},
  {text: "Daddy issues."},
  {text: "Mummy issues."},
  {text: "Crippling debt."},
  {text: "Abstinence"}
])
