WhiteCard.create([
  {text: "Bad bitches with fat asses."},
  {text: "Your ass cheeks on my face cheeks."},
  {text: "Pulling a shit-covered condom of Fentanyl out of a dead Slovenian’s asshole."},
  {text: "Shitting out a hot stack of pancakes and a pat of butter."},
  {text: "Being grossly unprepared for this jelly."},
  {text: "Waxing my asshole."},
  {text: "Pooping and then looking at the poop."},
  {text: "Carrying my poop around in a ziplock bag."},
  {text: "Tender anal love."},
  {text: "Cellulite."},
  {text: "Rubbing sage all over my butt cancer."},
  {text: "Blowing a fart hole in my yoga pants."},
  {text: "Showing everyone my lil’ dumper."},
  {text: "How good the booty taste."},
  {text: "Ruining my asshole with superglue."},
  {text: "Doing my duty to your booty."},
  {text: "That post-smack jiggle."},
  {text: "My faithful donkey Bathsheba."},
  {text: "An ass like two old Italian faces telling secrets."},
  {text: "An ass like two football helmets."},
  {text: "Tight, red baboon ass."},
  {text: "Sir Thomas Crapper, inventor of the toilet."},
  {text: "Sir Mix-a-lot."},
  {text: "The sun-ripen asses of Sicily."},
  {text: "Cheesy French anus."},
  {text: "Thick Ukrainian ass."},
  {text: "Me arse."},
  {text: "A killer’s diet of bush, cucumbers, and feathers."},
  {text: "A woman who is so smart that she can predict the movements of 300 birds."},
  {text: "Finding a nipple and being like “Oooh! That’s a nipple!”"},
  {text: "Getting Masturbated to."},
  {text: "Giving grandma crappy things she doesn’t like."},
  {text: "Ham finger."},
  {text: "Hands down the best eggnog I have ever had."},
  {text: "Insane empanadas."},
  {text: "Kim Kardashian, but with spider legs."},
  {text: "Laughing hysterically while my partner pours coffee into my eyes."},
  {text: "More olives than you could possibly understand."},
  {text: "Mr. Poop."},
  {text: "My disgusting pot-bellied boy."},
  {text: "P.F. Chang’s fusion of casual and formal cuisine."},
  {text: "Screaming “there’s a hawk up my ass!”"},
  {text: "Secret CIA moon prisons."},
  {text: "Sitting in the back of the plane, smoking a cigar and reading the Flickr privacy policy."},
  {text: "Some kind of mutated shrimp that can suck dick like a pro."},
  {text: "Some sort of unstoppable poo gun."},
  {text: "Stairs."},
  {text: "That shitty season of Mad Men where Sterling Cooper Draper Pryce gets destroyed by Daenerys Targaryen’s dragons."},
  {text: "The amount of emotions a peanut would be capable of holding."},
  {text: "The idea of a walrus."},
  {text: "The lesbians of Iowa."},
  {text: "The real story behind the yogurt that came out of Tina’s vagina."},
  {text: "The unspeakable secrets of the weasels."},
  {text: "These amazing testicles I’m about to share with you."},
  {text: "These awesome gadgets that track my every move."},
  {text: "These new jeans that look so cool but are actually so bad."},
  {text: "What I Doin’."},
  {text: "A pointless job at a soulless corporation."},
  {text: "Being terrified of a single bee."},
  {text: "Being young and in love in New York City."},
  {text: "Chemotherapy."},
  {text: "Delighting in the pain of others."},
  {text: "Forming a monogamous pairbond."},
  {text: "Getting my butt trapped hilariously in a tuba."},
  {text: "Getting sad for no reason."},
  {text: "Good ol’ fashioned face-to-face conversation."},
  {text: "Harnessing the power of steam!!!"},
  {text: "How good this cantaloupe feels on my penis."},
  {text: "Just hangin’ out, ya know?"},
  {text: "Like 50 mosquito bites."},
  {text: "Losing a loved one to Fox News."},
  {text: "Really tall people."},
  {text: "Saying “what’s that?” And then stealing a french fry."},
  {text: "Sucking all the oil out of the planet and fucking off to Mars."},
  {text: "The bomb strapped to my chest."},
  {text: "The joy of song."},
  {text: "The salmon."},
  {text: "The unspeakable horrors of factory farming."},
  {text: "The whole Jeffrey Epstein thing."},
  {text: "This horrible thing called twitter."},
  {text: "Three hours of pimple-popping videos."},
  {text: "Unwelcome sexual attention from grown men."},
  {text: "Using words to communicate."},
  {text: "War with China."},
  {text: "Watching the life drain from the eyes of my son’s killer."},
  {text: "A 12-foot scepter of bone."},
  {text: "A basketball that screams every time it gets bounced."},
  {text: "A bear."},
  {text: "A big hole."},
  {text: "A big hot fire that's burning everybody."},
  {text: "A big, big, big, and I mean BIG big."},
  {text: "A big, sloppy blowjob from a mean, tired cowboy."},
  {text: "A bird that dies."},
  {text: "A bold red lip."},
  {text: "A button that when you press it, there's jazz."},
  {text: "A crab rangoon."},
  {text: "A cat with… hands."},
  {text: "A Christmas feast of goose and jellies."},
  {text: "A concerning amount of white people."},
  {text: "A couple of cold ones."},
  {text: "A family of raccoons."},
  {text: "A four-hour depression nap."},
  {text: "A full-on panic attack."},
  {text: "A garbage clown who makes no one laugh and should die."},
  {text: "A hamburger on a string that keeps getting pulled away."},
  {text: "A hateful 30-year marriage."},
  {text: "A little boy with big dreams and potatoes for hands."},
  {text: "A little girl with a knife."},
  {text: "A little sewer girl strangling a pigeon."},
  {text: "A little taste of penis."},
  {text: "A magician fucking up over and over again."},
  {text: "A penis that gets too hard and explodes blood."},
  {text: "A piping-hot casserole filled with beans and hair."},
  {text: "A poop emergency."},
  {text: "A powerful philosopher named Brainhead."},
  {text: "A Pringle."},
  {text: "A Puerto Rican minotaur from the Bronx."},
  {text: "A racist boomerang that only comes back if you're white."},
  {text: "A real cum-dumpster of a saxophonist."},
  {text: "A real job with insurance and your taxes taken out and everything."},
  {text: "A sticky tree hole full of pancake sauce."},
  {text: "A stinky hoo-ha."},
  {text: "A toothless woman gumming on a peach."},
  {text: "A urinary tract infection."},
  {text: "A vagina that beatboxes when it's horny."},
  {text: "A whole different way of talking called Spanish."},
  {text: "Accusing a powerful man of sexual assault."},
  {text: "Acquiring a gun very easily."},
  {text: "Acting white."},
  {text: "All manners of honors."},
  {text: "All my dead sisters."},
  {text: "All types of girls, even ugly ones."},
  {text: "An 800-foot-long pool noodle."},
  {text: "An ambitious woman who wears pants."},
  {text: "An elite squad known as the Special Victims Unit."},
  {text: "Anything Asian."},
  {text: "As ass like a bag of pool balls."},
  {text: "Assembling IKEA furniture."},
  {text: "Beef."},
  {text: "Being hunted by giant eagles."},
  {text: "Being inside me."},
  {text: "Being seen reading Infinite Jest."},
  {text: "Being shitty to everyone and late for everything."},
  {text: "Big beefy baseball boys."},
  {text: "Big Italian women making the spicy sauce."},
  {text: "Bimpy, the small styrofoam ball we all jack off into."},
  {text: "Bipolar Disorder."},
  {text: "Blowing into the penis so that the balls inflate."},
  {text: "Blue smoke coming out of my anus."},
  {text: "Canada's worst mangoes."},
  {text: "Carbs."},
  {text: "Carlos Santana's horrible wailing guitar."},
  {text: "Certain things, but not others."},
  {text: "Chinese people."},
  {text: "Chowder."},
  {text: "Clearly asking for no cucumbers in my salad, and yet here we are."},
  {text: "Clippy from Microsoft Office."},
  {text: "Colluding with Russia."},
  {text: "Corn."},
  {text: "Country music legend Toby Keith."},
  {text: "Crunchy snacks for big, flappy mouth."},
  {text: "Cultural appropriation."},
  {text: "Curly fries so good you quit ISIS."},
  {text: "Dating a Republican."},
  {text: "Death."},
  {text: "Déjà vu."},
  {text: "Denying climate change."},
  {text: "Doing ho shit."},
  {text: "Doing it doggy, no kissing."},
  {text: "Doing stuff bad."},
  {text: "Drake."},
  {text: "Driving to a Walmart parking lot and staring into the distance for eight hours."},
  {text: "Eating pussy bad."},
  {text: "Ejaculating a quart of hollandaise sauce."},
  {text: "Elon Musk."},
  {text: "Enticing a hummingbird to drink nectar out of my urethra."},
  {text: "Fascism."},
  {text: "Fat."},
  {text: "Fingering each other's buttholes."},
  {text: "Foul vegan shits."},
  {text: "Free two-day shipping with Amazon Prime."},
  {text: "Fresh Air with Terry Gross."},
  {text: "Funneling money through a series of shell companies."},
  {text: "Getting #MeToo'd."},
  {text: "Getting banished to the Shadow Realm."},
  {text: "Getting depressed and super fat."},
  {text: "Getting fisted by a man with no fingers."},
  {text: "Getting half-hard and trying to smoosh it in."},
  {text: "Getting herpes from Bruce Willis."},
  {text: "Getting Mommy another beer."},
  {text: "Getting tanned, jacked, and juicy."},
  {text: "Going 'oink oink' like a nasty little pig boy."},
  {text: "Good, clean Christian comedy."},
  {text: "Having tuna sandwiches with my favorite honkies."},
  {text: "Hard-hitting investigative journalism."},
  {text: "Having a wonderful time at the zoo."},
  {text: "Having no legs, just toes."},
  {text: "Having thirty sons named Chad."},
  {text: "Healthcare.gov."},
  {text: "Hiding from border patrol."},
  {text: "Hiking up a hillside covered in bear semen yelling 'I'm the queen of the forest!'"},
  {text: "Hoopnugget, the game where you throw a nugget into a hoop."},
  {text: "How many bagels I can fit on my penis."},
  {text: "How quiet the forest is."},
  {text: "Huffing and puffing and blowing my stepdad."},
  {text: "Hunting white men for sport."},
  {text: "Hush money."},
  {text: "Interrupting women."},
  {text: "Jeremy and his stupid, annoying, dumb, hard, beautiful body."},
  {text: "Jörmungandr the World Serpent."},
  {text: "Joyless, wooden Soviet toys."},
  {text: "Just a Luna bar for lunch."},
  {text: "Kanye West but if he were an old Japanese farmer."},
  {text: "Korean barbecue."},
  {text: "Leading a country to war on false pretenses."},
  {text: "Leading children around with a magical flute."},
  {text: "Letting that pussy breathe."},
  {text: "Letting this loser eat me out."},
  {text: "Licking the toilet as Mistress commands."},
  {text: "Life."},
  {text: "Little Debbie and her mom, Full-Size Deborah."},
  {text: "Lotion."},
  {text: "Loving America."},
  {text: "Magic: The Gathering."},
  {text: "Making direct eye contact with a horse's asshole."},
  {text: "Mark Zuckerberg."},
  {text: "Maybe getting a little involved in selling heroin sometimes."},
  {text: "Melania Trump."},
  {text: "Murdering our parents."},
  {text: "My buddy Jeff."},
  {text: "My daughter fucking my boyfriend."},
  {text: "My math teacher's bulge."},
  {text: "My real dad."},
  {text: "My secret butt."},
  {text: "My son's dipshit friends."},
  {text: "My son's husband's huge cock."},
  {text: "My wife. (in Borat voice)"},
  {text: "Naked Dad."},
  {text: "Netflix."},
  {text: "New DNA evidence exonerating OJ Simpson."},
  {text: "Nipples the size of CDs."},
  {text: "None of your damn business."},
  {text: "Nonsexual activiities, such as roller skating."},
  {text: "Not being a part of my son's life."},
  {text: "Oral."},
  {text: "Outdated gender norms."},
  {text: "Owing a lot of money to some very bad people."},
  {text: "Panda Express."},
  {text: "Panic and confusion."},
  {text: "Pissin' me paants."},
  {text: "Politics."},
  {text: "Poppin' that pussy."},
  {text: "Preparing my asshole for sex."},
  {text: "Pretending golf is fun."},
  {text: "Prison."},
  {text: "Pulling a sick, shit-covered raccoon out of the toilet and nursing it back to health."},
  {text: "Pulling the butt cheeks apart so the fart comes out quieter."},
  {text: "Pushing my boob up to lick the nipple."},
  {text: "Putting dirty dishes in the sink and hoping someone else deals with them."},
  {text: "Quality, affordable menswear."},
  {text: "Reparations for slavery."},
  {text: "Representing the entire black community."},
  {text: "Respecting woman."},
  {text: "Rubbing my clit with a handgun."},
  {text: "Sandwich."},
  {text: "Schindler's List."},
  {text: "Setting boundaries with co-workers."},
  {text: "Sewing two hamsters together to make a Double Hamster Supreme."},
  {text: "Shit."},
  {text: "Shitting perfectly into a hot dog bun."},
  {text: "Slaves."},
  {text: "Slowly releasing a huge fart over the course of two minutes."},
  {text: "Sluts, whores, and bitches."},
  {text: "Small plates, or tapas if you will."},
  {text: "Some cracker-ass motherfucker."},
  {text: "Some light choking."},
  {text: "Square dancing with other racists."},
  {text: "Stapling a butterfly to a cow."},
  {text: "Staying hydrated."},
  {text: "Sticking my hard rat dick in my girlfiend's wet rat pussy."},
  {text: "Substituting sweet potato fries for $2."},
  {text: "Sucking the caviar straight out of a fish's pussy."},
  {text: "Suddenly feeling really sad for 40 years."},
  {text: "Swordplay."},
  {text: "Taking a dump."},
  {text: "Tar."},
  {text: "The Asshole Destroyer 3000."},
  {text: "The Audi Sign-and-Drive Sales Event."},
  {text: "The awesome power of the Lord."},
  {text: "The beautiful backpacks of JanSport."},
  {text: "The boy who sucks the farts our of my sweatpants."},
  {text: "The coming race war."},
  {text: "The current political climate."},
  {text: "The cutest fucking shoes I've ever seen."},
  {text: "The end of all life on Earth."},
  {text: "The express written consent of the National Basketball Association."},
  {text: "The fact that time is moving backwards right now and nobody's noticing."},
  {text: "The harsh reality that all horses are people in horse costumes."},
  {text: "The incredible Gary, he'll suck your nipples."},
  {text: "The kind of porn with poop."},
  {text: "The King of Jews."},
  {text: "The little-known fact that Polish people don't dream."},
  {text: "The man in the basement."},
  {text: "The man who fucks me and my wife."},
  {text: "The Moon."},
  {text: "The NRA."},
  {text: "The pelican that will one day eat Scarlett Johansson's baby."},
  {text: "The persecution of Buddhists by the American-backed government of South Vietnam."},
  {text: "The pleasure of watching my boys wolf down my pot roast and scamper into the woods."},
  {text: "The rock after which Dwayne Johnson was named."},
  {text: "The South rising again."},
  {text: "The wonderful giant spoon known as 'ladle.'"},
  {text: "The world's largest baby, weighing over 700 pounds."},
  {text: "The worm that ate my penis and is now my penis."},
  {text: "These breasts of mine."},
  {text: "This boring-ass white bitch from work."},
  {text: "This kid I found."},
  {text: "Thoughts and prayers."},
  {text: "Three men and three hot dogs."},
  {text: "Throwing a man by his big penis."},
  {text: "Thrusting and grunting."},
  {text: "Thumb, the King of the Fingers."},
  {text: "Tiny, sour kisses from a lemon dwarf."},
  {text: "Travolta."},
  {text: "Trees with human skin."},
  {text: "Turning poor people against each other so they don't pay attention to economic inequality."},
  {text: "Twirling a cane, popping it into my anus, and giving a tip of the top hat."},
  {text: "Uncles."},
  {text: "Uncut daddy dick."},
  {text: "Violating the Geneva Convention."},
  {text: "Voldemort."},
  {text: "Voter suppression."},
  {text: "What looked like a chemical weapons facility but turned out to be a children's hospital."},
  {text: "Women in positions of power."},
  {text: "Yo stanky ass."},
  {text: "Yogurt that moans in pleasure as you eat it."},
  {text: "Your little booty in them underpants."},
  {text: "Your mouth."},
  {text: "Yummy yummy yummy yummy rat pussy."}
])

BlackCard.create([
  {text: "My anaconda don’t want none unless you got __, hun.", pick_amount: "1"},
  {text: "My homeboys tried to warn me, but _ makes me so horny.", pick_amount: "1"},
  {text: "I like __ and I cannot lie!", pick_amount: "1"},
  {text: "Do not go gentle into that good night. Rage, rage against __?", pick_amount: "1"},
  {text: "Sure, sex is great, but have you tried _?", pick_amount: "1"},
  {text: "Ain't it nifty? Barb and Bob hit 50! So get off your ass and raise a glass to 50 years of ______.", pick_amount: "1"},
  {text: "Duuuuuuude. You have got to go to space. ______ is awesome in space.", pick_amount: "1"},
  {text: "Five, four, three, two, one…. ______!", pick_amount: "1"},
  {text: "For hunting in the King's forest, I hereby sentence you to death by ______.", pick_amount: "1"},
  {text: "Give me ten good men and 48 hours. I'll get you ______.", pick_amount: "1"},
  {text: "Goldfinger! He's the man, the man with _______.", pick_amount: "1"},
  {text: "Goodbye, ______, hello _____!", pick_amount: "2"},
  {text: "Here's a little something I learned in business school: The customer is always ______.", pick_amount: "1"},
  {text: "Hey, honey. For the bedroom, were you thinking, “Robin's Egg Blue“ or ______Pink?“", pick_amount: "1"},
  {text: "I hate this job. I hate this place. Most of all, I hate ______. I quit.", pick_amount: "1"},
  {text: "I have solved politics. My solution is ______.", pick_amount: "1"},
  {text: "I so drunk I ______.", pick_amount: "1"},
  {text: "I swear to God I'm gonna murder my husband if he doesn't shut the fuck up about ______.", pick_amount: "1"},
  {text: "In bookstores now: “From ______ to ______: A memoir.“", pick_amount: "2"},
  {text: "In Radiohead's new single, Thom Yorke repeats the phrase “______“ dozens of times over a skittering drum beat.", pick_amount: "1"},
  {text: "It's finally happening! I'm finally doing it! Yes! It's time for ______!", pick_amount: "1"},
  {text: "It's late at night. You're in bed with your lover, Patrick Stewart. He leans over with a twinkle in his eye and asks “How about ______?“", pick_amount: "1"},
  {text: "It's the 21st century. A woman shouldn't have to apologize for ______.", pick_amount: "1"},
  {text: "Ladies and gentlemen, I propose a two-pronged plan. The first prong will be ______, and the second prong will be ______.", pick_amount: "2"},
  {text: "Live from Universal Studios, it's America's favorite game show! “______ or ______?“", pick_amount: "2"},
  {text: "Millions of copies sold! Donald Trump's “The Art of _______.“", pick_amount: "1"},
  {text: "New at TGI Fridays! It's what you've been waiting for: The ______ Burger.", pick_amount: "1"},
  {text: "Oh no! Here it comes! Ohhhhh god! It's ______.", pick_amount: "1"},
  {text: "Oh you haaaaaaave to see this new documentary on Netflix. I don't want to give anything away, but let's just say it will change the way you look at ______.", pick_amount: "1"},
  {text: "Oh, the weather outside is frightful. But ______ is so delightful.", pick_amount: "1"},
  {text: "One, two, three and to the four, Snoop Doggy Dogg and Dr. Dre is ______.", pick_amount: "1"},
  {text: "Personal foul: ______. 15-yard penalty. Automatic first down.", pick_amount: "1"},
  {text: "Rub a dub dub, ______ in a tub!", pick_amount: "1"},
  {text: "Say it loud! I'm ______ and I'm proud!", pick_amount: "1"},
  {text: "Seriously guys, there's nothing funny about ______.", pick_amount: "1"},
  {text: "Sweetheart, you and your sister escel in different ways. She's got her violin, and you've got ______.", pick_amount: "1"},
  {text: "That's bullshit! They can't fire me for _______!", pick_amount: "1"},
  {text: "The sequel is here! Get Ready for ______2: ______.", pick_amount: "2"},
  {text: "Times have changed, girlfriend. If you want to meet people in New York, you got to be down for _______.", pick_amount: "1"},
  {text: "Unfortunately, no one can be told what ______ is. You have to experience it for yourself.", pick_amount: "1"},
  {text: "What has my life become? I'm jerking off to a video called “co-ed absolutely destroyed by ______.“", pick_amount: "1"},
  {text: "What sounds great after four margaritas?", pick_amount: "1"},
  {text: "What's hot, smelly, and about to die?", pick_amount: "1"},
  {text: "What's secretly a Russian plot to destabilize the West?", pick_amount: "1"},
  {text: "What's up, YouTube? User DanTheMan wanted to see ______, so here we go.", pick_amount: "1"},
  {text: "Why did the chicken cross the road?", pick_amount: "1"},
  {text: "Why my mustache smell so bad?", pick_amount: "1"},
  {text: "Yeah that's so hot. I'm so close. Talk about ______ again! OH I'M CUMMING!", pick_amount: "1"},
  {text: "You can call me David Copperfield, because I'm about to make ______ disappear.", pick_amount: "1"},
  {text: "You city folk would never understand the quiet dignity of _______.", pick_amount: "1"}
])
