# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])

WhiteCard.create([
  {text: "A fart so powerful that it wakes the giants from their thousand-year slumber."},
  {text: "Laying an egg."},
  {text: "Seeing Grandma naked."},
  {text: "The Rapture."},
  {text: "The Hamburglar."},
  {text: "BATMAN!"},
  {text: "Coat hanger abortions."},
  {text: "Swooping."},
  {text: "Putting things where they go."},
  {text: "Kanye West."},
  {text: "Smegma."},
  {text: "Bingeing and purging."},
  {text: "Half-assed foreplay."},
  {text: "Teenage pregnancy."},
  {text: "A pyramid of severed heads."},
  {text: "My genitals."},
  {text: "Flightless birds."},
  {text: "Dead birds everywhere."},
  {text: "Chemical weapons."},
  {text: "Passive aggressive Post-it notes."},
  {text: "Wet dreams."},
  {text: "These hoes."},
  {text: "Kissing grandma on the forehead and turning off her life support."},
  {text: "Punching a congressman in the face."},
  {text: "Republicans."},
  {text: "Kamikaze pilots."},
  {text: "A falcon with a cap on its head."},
  {text: "Free samples."},
  {text: "Lactation."},
  {text: "RoboCop."},
  {text: "Inappropriate yodeling."},
  {text: "Fucking my sister."},
  {text: "My Uber driver, Pavel."},
  {text: "Preteens."},
  {text: "Darth Vader."},
  {text: "Adderall.®"},
  {text: "My neck,"},
  {text: "my back,"},
  {text: "my pussy, and my crack."},
  {text: "Women of color."},
  {text: "Casually suggesting a threesome."},
  {text: "Sexual peeing."},
  {text: "The placenta."},
  {text: "Establishing dominance."},
  {text: "My inner demons."},
  {text: "However much weed $20 can buy."},
  {text: "A disappointing birthday party."},
  {text: "William Shatner."},
  {text: "Mutually assured destruction."},
  {text: "Rectangles."},
  {text: "The Hustle."},
  {text: "Kourtney, Kim, Khloe, Kendall, and Kylie."},
  {text: "Pictures of boobs."},
  {text: "Getting really high."},
  {text: "Ruth Bader Ginsburg brutally gaveling your penis."},
  {text: "Meth."},
  {text: "A whole thing of butter."},
  {text: "Pixelated bukkake."},
  {text: "Racism."},
  {text: "Huge biceps."},
  {text: "Executing a hostage every hour."},
  {text: "Gloryholes."},
  {text: "Fellowship in Christ."},
  {text: "Getting drugs off the street and into my body."},
  {text: "Itchy pussy."},
  {text: "Waiting till marriage."},
  {text: "Autocannibalism."},
  {text: "White people."},
  {text: "Having anuses for eyes."},
  {text: "The magic of live theatre."},
  {text: "NBA superstar LeBron James."},
  {text: "Pooping back and forth. Forever."},
  {text: "The South."},
  {text: "Telling a shitty story that goes nowhere."},
  {text: "Being a woman."},
  {text: "The Boy Scouts of America."},
  {text: "Heartwarming orphans."},
  {text: "Fiery poops."},
  {text: "Some of the best rappers in"},
  {text: "the game."},
  {text: "The Russians."},
  {text: "Dark and mysterious forces beyond our control."},
  {text: "Queefing."},
  {text: "Soup that is too hot."},
  {text: "Drinking alone."},
  {text: "Child abuse."},
  {text: "Being able to talk to elephants."},
  {text: "A stray pube."},
  {text: "My ex-wife."},
  {text: "Count Chocula."},
  {text: "Vomiting seafood and bleeding anally."},
  {text: "Pooping in a laptop and closing it."},
  {text: "Italians."},
  {text: "10,000 Syrian refugees."},
  {text: "Diversity."},
  {text: "Giving birth to the Antichrist."},
  {text: "What that mouth do."},
  {text: "Racially-biased SAT questions."},
  {text: "Child beauty pageants."},
  {text: "Huffing spray paint."},
  {text: "My vagina."},
  {text: "Her Majesty, Queen Elizabeth II."},
  {text: "Being marginalized."},
  {text: "A micropenis."},
  {text: "Hot people."},
  {text: "Extremely tight pants."},
  {text: "Vehicular manslaughter."},
  {text: "African children."},
  {text: "Elderly Japanese men."},
  {text: "Arnold Schwarzenegger."},
  {text: "A mopey zoo lion."},
  {text: "Auschwitz."},
  {text: "The Big Bang."},
  {text: "Penis breath."},
  {text: "The Underground Railroad."},
  {text: "Morgan Freeman’s voice."},
  {text: "My black ass."},
  {text: "Grandma."},
  {text: "Being a dick to children."},
  {text: "Drinking out of the toilet and eating garbage."},
  {text: "The bombing of Nagasaki."},
  {text: "My ugly face and bad personality."},
  {text: "Jews, gypsies, and homosexuals."},
  {text: "Used panties."},
  {text: "Covering myself with Parmesan cheese and chili flakes because I am pizza."},
  {text: "Having big dreams but no realistic way to achieve them."},
  {text: "The miracle of childbirth."},
  {text: "Emerging from the sea and rampaging through Tokyo."},
  {text: "Soft, kissy missionary sex."},
  {text: "Natural selection."},
  {text: "Prescription pain killers."},
  {text: "Alexandria Ocasio-Cortez."},
  {text: "An old guy who’s almost dead."},
  {text: "Seven dead"},
  {text: "and three in critical condition."},
  {text: "Looking in the mirror, applying lipstick, and whispering “tonight, you will have sex with Tom Cruise.”"},
  {text: "Sitting on my face and telling me I’m garbage."},
  {text: "Being on fire."},
  {text: "A Fleshlight.®"},
  {text: "The past."},
  {text: "Not reciprocating oral sex."},
  {text: "A balanced breakfast."},
  {text: "The cool, refreshing taste of Pepsi.®"},
  {text: "Bananas."},
  {text: "Peeing a little bit."},
  {text: "Powerful thighs."},
  {text: "Donald J. Trump."},
  {text: "My good bra."},
  {text: "Sweet, sweet vengeance."},
  {text: "Poverty."},
  {text: "A Mexican."},
  {text: "Juuling."},
  {text: "The Three-Fifths Compromise."},
  {text: "Eating a hard boiled egg out of my husband’s asshole."},
  {text: "Oompa-Loompas."},
  {text: "50 mg of Zoloft daily."},
  {text: "Getting fingered."},
  {text: "Filling my briefcase with business stuff."},
  {text: "Fading away into nothingness."},
  {text: "Expecting a burp and vomiting on the floor."},
  {text: "An octopus giving seven handjobs and smoking a cigarette."},
  {text: "Sperm whales."},
  {text: "Pac-Man uncontrollably guzzling cum."},
  {text: "The wonders of the Orient."},
  {text: "Jobs."},
  {text: "Throwing grapes at a man until he loses touch with reality."},
  {text: "Getting crushed by a vending machine."},
  {text: "Cuddling."},
  {text: "Ronald Reagan."},
  {text: "A tiny horse."},
  {text: "Brown people."},
  {text: "How bad my daughter fucked up her dance recital."},
  {text: "Only dating Asian women."},
  {text: "Judging everyone."},
  {text: "AIDS."},
  {text: "Hospice care."},
  {text: "Gay conversion therapy."},
  {text: "A pangender octopus who roams the cosmos in search of love."},
  {text: "A Bop It.TM"},
  {text: "Getting cummed on."},
  {text: "Dick pics."},
  {text: "Radical Islamic terrorism."},
  {text: "A gossamer stream of jizz that catches the light as it arcs through the morning air."},
  {text: "Leprosy."},
  {text: "Puppies!"},
  {text: "An older woman who knows her way around the penis."},
  {text: "Ethnic cleansing."},
  {text: "A salad for men that’s made"},
  {text: "of metal."},
  {text: "The Devil himself."},
  {text: "The Pope."},
  {text: "How far I can get my own penis"},
  {text: "up my butt."},
  {text: "Danny DeVito."},
  {text: "Accepting the way things are."},
  {text: "Being fat and stupid."},
  {text: "A salty surprise."},
  {text: "Consensual sex."},
  {text: "Necrophilia."},
  {text: "Black people."},
  {text: "Some punk kid who stole my turkey sandwich."},
  {text: "A bowl of mayonnaise and human teeth."},
  {text: "The true meaning of Christmas."},
  {text: "Girls."},
  {text: "PTSD."},
  {text: "Hobos."},
  {text: "Viagra.®"},
  {text: "Academy Award winner Meryl Streep."},
  {text: "Poopy diapers."},
  {text: "Pulling out."},
  {text: "Stalin."},
  {text: "Doin’ it in the butt."},
  {text: "A windmill full of corpses."},
  {text: "The glass ceiling."},
  {text: "My balls on your face."},
  {text: "A saxophone solo."},
  {text: "Mike Pence."},
  {text: "An unwanted pregnancy."},
  {text: "Harry Potter erotica."},
  {text: "8 oz. of sweet Mexican black-tar heroin."},
  {text: "Opposable thumbs."},
  {text: "Nicolas Cage."},
  {text: "Lena Dunham."},
  {text: "Invading Poland."},
  {text: "Giving 110%."},
  {text: "Sex with animals."},
  {text: "Liberals."},
  {text: "A horde of Vikings."},
  {text: "Geese."},
  {text: "Making a pouty face."},
  {text: "Judge Judy."},
  {text: "Illegal immigrants."},
  {text: "Crumbs all over the god damn carpet."},
  {text: "A bird that shits human turds."},
  {text: "My sex life."},
  {text: "The clitoris."},
  {text: "A micropig wearing a tiny raincoat and booties."},
  {text: "Me time."},
  {text: "Lumberjack fantasies."},
  {text: "Being a motherfucking sorcerer."},
  {text: "Balls."},
  {text: "Farting and walking away."},
  {text: "Dying."},
  {text: "Men."},
  {text: "David Bowie flying in on a tiger made of lightning."},
  {text: "Fear itself."},
  {text: "Former President George W. Bush."},
  {text: "Getting naked and watching Nickelodeon."},
  {text: "Boogers."},
  {text: "Whipping it out."},
  {text: "AXE Body Spray."},
  {text: "Agriculture."},
  {text: "Sex with Patrick Stewart."},
  {text: "Mansplaining."},
  {text: "Fragile masculinity."},
  {text: "Hot cheese."},
  {text: "Alcoholism."},
  {text: "An oversized lollipop."},
  {text: "The Holy Bible."},
  {text: "Gandhi."},
  {text: "An erection that lasts longer than four hours."},
  {text: "An endless stream of diarrhea."},
  {text: "A good sniff."},
  {text: "The arrival of the pizza."},
  {text: "Oprah."},
  {text: "Hillary Clinton’s emails."},
  {text: "The Jews."},
  {text: "The only gay person in a hundred miles."},
  {text: "Sexual tension."},
  {text: "Fancy Feast.®"},
  {text: "Sniffing and kissing my feet."},
  {text: "Committing suicide."},
  {text: "Wizard music."},
  {text: "Hurting those closest to me."},
  {text: "World peace."},
  {text: "One titty hanging out."},
  {text: "Puberty."},
  {text: "Braiding three penises into"},
  {text: "a Twizzler."},
  {text: "GoGurt.®"},
  {text: "My fat daughter."},
  {text: "A sad handjob."},
  {text: "The Red Hot Chili Peppers."},
  {text: "J.D. Power and his associates."},
  {text: "Men discussing their feelings in an emotionally healthy way."},
  {text: "Running out of semen."},
  {text: "Emotions."},
  {text: "Spontaneous human combustion."},
  {text: "Finger painting."},
  {text: "A Super SoakerTM full of cat pee."},
  {text: "Battlefield amputations."},
  {text: "Nachos for the table."},
  {text: "Selling crack to children."},
  {text: "Pedophiles."},
  {text: "Catapults."},
  {text: "The Force."},
  {text: "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying."},
  {text: "Strong female characters."},
  {text: "The opiod epidemic."},
  {text: "German Chancellor Angela Merkel."},
  {text: "Serfdom."},
  {text: "Still being a virgin."},
  {text: "A lifetime of sadness."},
  {text: "Menstrual rage."},
  {text: "My little boner."},
  {text: "The rhythms of Africa."},
  {text: "Nipple blades."},
  {text: "Little boy penises."},
  {text: "Daniel Radcliffe’s delicious asshole."},
  {text: "Blowing my boyfriend so hard he shits."},
  {text: "Unfathomable stupidity."},
  {text: "Erectile dysfunction."},
  {text: "Tentacle porn."},
  {text: "The penny whistle solo from “My Heart Will Go On.”"},
  {text: "Throwing a virgin into a volcano."},
  {text: "Listening to her problems without trying to solve them."},
  {text: "Tearing that ass up like wrapping paper on Christmas morning."},
  {text: "The violation of our most basic human rights."},
  {text: "A good, strong gorilla."},
  {text: "Getting into a pretty bad car accident."},
  {text: "LunchablesTM."},
  {text: "Spirit Airlines."},
  {text: "Saying “I love you.”"},
  {text: "Owning and operating a Chili’s franchise."},
  {text: "A bleached asshole."},
  {text: "Smallpox blankets."},
  {text: "The guys from Queer Eye."},
  {text: "Muhammad (Peace Be Upon Him)."},
  {text: "Dick fingers."},
  {text: "Anal beads."},
  {text: "Horse meat."},
  {text: "Worshipping that pussy."},
  {text: "Teaching a robot to love."},
  {text: "Vladimir Putin."},
  {text: "The American Dream."},
  {text: "Dead babies."},
  {text: "A fetus."},
  {text: "Forced sterilization."},
  {text: "A white ethnostate."},
  {text: "Three dicks at the same time."},
  {text: "Dead parents."},
  {text: "The Great Depression."},
  {text: "Explosions."},
  {text: "A man on the brink of orgasm."},
  {text: "Assless chaps."},
  {text: "The Trail of Tears."},
  {text: "Goblins."},
  {text: "My soul."},
  {text: "Seething with quiet resentment."},
  {text: "Fox News."},
  {text: "Women’s suffrage."},
  {text: "This month’s mass shooting."},
  {text: "The female orgasm."},
  {text: "The wifi password."},
  {text: "A bag of magic beans."},
  {text: "A snapping turtle biting the tip of your penis."},
  {text: "Land mines."},
  {text: "Jerking off into a pool of children’s tears."},
  {text: "Poorly-timed Holocaust jokes."},
  {text: "Women in yogurt commercials."},
  {text: "Genuine human connection."},
  {text: "Friction."},
  {text: "One trillion dollars."},
  {text: "The gays."},
  {text: "Fake tits."},
  {text: "A bitch slap."},
  {text: "The milkman."},
  {text: "Full frontal nudity."},
  {text: "Pretending to care."},
  {text: "The inevitable heat death of the universe."},
  {text: "White privilege."},
  {text: "The Blood of Christ."},
  {text: "Barely making $25,000 a year."},
  {text: "My abusive boyfriend who really isn’t so bad once you get to know him."},
  {text: "A homoerotic volleyball montage."},
  {text: "All-you-can-eat shrimp for $8.99."},
  {text: "Raptor attacks."},
  {text: "A middle-aged man on roller skates."},
  {text: "Self-loathing."},
  {text: "German dungeon porn."},
  {text: "Your weird brother."},
  {text: "A three-way with my wife and Shaquille O’Neal."},
  {text: "Science."},
  {text: "50,000 volts straight to the nipples."},
  {text: "Permanent Orgasm-Face Disorder."},
  {text: "Wondering if it’s possible to get some of that salsa to go."},
  {text: "Switching to Geico®."},
  {text: "My cheating son-of-a-bitch husband."},
  {text: "Having sex for the first time."},
  {text: "An AR-15 assault rifle."},
  {text: "Being rich."},
  {text: "A much younger woman."},
  {text: "The homosexual agenda."},
  {text: "The Kool-Aid Man."},
  {text: "Doing the right thing."},
  {text: "Shutting up so I can watch the game."},
  {text: "Justin Bieber."},
  {text: "Ghosts."},
  {text: "Vigorous jazz hands."},
  {text: "Police brutality."},
  {text: "Rap music."},
  {text: "Exactly what you’d expect."},
  {text: "Sideboob."},
  {text: "Mouth herpes."},
  {text: "Incest."},
  {text: "God."},
  {text: "Licking things to claim them as your own."},
  {text: "The Bachelorette season finale."},
  {text: "Old-people smell."},
  {text: "Aaron Burr."},
  {text: "Spaghetti? Again?"},
  {text: "Becoming a blueberry."},
  {text: "An M. Night Shyamalan plot twist."},
  {text: "Yeast."},
  {text: "Poor people."},
  {text: "How amazing it is to be on mushrooms."},
  {text: "Some god damn peace and quiet."},
  {text: "Some foundation, mascara, and a touch of blush."},
  {text: "Penis envy."},
  {text: "The KKK."},
  {text: "Holding down a child and farting all over him."},
  {text: "Solving problems with violence."},
  {text: "Going an entire day without masturbating."},
  {text: "Sunshine and rainbows."},
  {text: "Dry heaving."},
  {text: "Breaking out into song and dance."},
  {text: "The heart of a child."},
  {text: "Waking up half-naked in a Denny’s parking lot."},
  {text: "Active listening."},
  {text: "A fuck-ton of almonds."},
  {text: "Shiny objects."},
  {text: "My collection of Japanese sex toys."},
  {text: "My bright pink fuckhole."},
  {text: "Seppuku."},
  {text: "Dwayne “The Rock” Johnson."},
  {text: "Therapy."},
  {text: "More elephant cock than I bargained for."},
  {text: "Tap dancing like there’s no tomorrow."},
  {text: "Seeing my father cry."},
  {text: "Bill Nye the Science Guy."},
  {text: "Bitches."},
  {text: "Bubble butt bottom boys."},
  {text: "Inserting a Mason jar into my anus."},
  {text: "Estrogen."},
  {text: "Fucking the weatherman on live television."},
  {text: "Masturbating."},
  {text: "Cardi B."},
  {text: "Explaining how vaginas work."},
  {text: "Multiple stab wounds."},
  {text: "Slaughtering innocent civilians."},
  {text: "A really cool hat."},
  {text: "Completely unwarranted confidence."},
  {text: "Touching a pug right on his penis."},
  {text: "The Patriarchy."},
  {text: "Not wearing pants."},
  {text: "Foreskin."},
  {text: "Firing a rifle into the air while balls deep in a squealing hog."},
  {text: "My relationship status."},
  {text: "Bees?"},
  {text: "Nazis."},
  {text: "Object permanence."},
  {text: "Chainsaws for hands."},
  {text: "Not vaccinating my children because I am stupid."},
  {text: "Repression."},
  {text: "Murder."},
  {text: "Memes."},
  {text: "Hope."},
  {text: "A ball of earwax, semen, and toenail clippings."},
  {text: "An Oedipus complex."},
  {text: "A little boy who won’t shut the fuck up about dinosaurs."},
  {text: "Some guy."},
  {text: "Barack Obama."},
  {text: "Heteronormativity."},
  {text: "Spectacular abs."},
  {text: "Poor life choices."},
  {text: "All the dudes I’ve fucked."},
  {text: "The entire Mormon Tabernacle Choir."},
  {text: "Man meat."},
  {text: "A sea of troubles."},
  {text: "Natural male enhancement."},
  {text: "Announcing that"},
  {text: "I am about to cum."},
  {text: "Chunks of dead hitchhiker."},
  {text: "Drowning the kids in the bathtub."},
  {text: "The screams... the terrible screams."},
  {text: "The Amish."},
  {text: "A brain tumor."},
  {text: "Cards Against Humanity."},
  {text: "24-hour media coverage"},
  {text: "A beached whale."},
  {text: "A big black dick."},
  {text: "A bloody pacifier."},
  {text: "A crappy little hand."},
  {text: "A fat bald man from the internet."},
  {text: "A low standard of living."},
  {text: "A nuanced critique."},
  {text: "A panty raid."},
  {text: "A passionate Latino lover."},
  {text: "A plunger to the face."},
  {text: "A rival dojo."},
  {text: "A smiling black man, a latina businesswoman, a cool asian, and some whites."},
  {text: "A web of lies."},
  {text: "A woman scorned."},
  {text: "An atomic wedgie."},
  {text: "An Etsy steampunk strap-on."},
  {text: "An evil man in evil clothes."},
  {text: "André the Giant’s enormous, leathery scrotum."},
  {text: "Apologizing."},
  {text: "Appreciative snapping."},
  {text: "Ashton Kutcher."},
  {text: "Beating your wives."},
  {text: "Being a busy adult with many important things to do."},
  {text: "Being a dinosaur."},
  {text: "Blaxploitation."},
  {text: "Bosnian chicken farmers."},
  {text: "Breaking nip slip news."},
  {text: "Carnies."},
  {text: "Clams."},
  {text: "Clenched butt cheeks."},
  {text: "Coughing into a vagina."},
  {text: "Cutting."},
  {text: "Dancing with a broom."},
  {text: "Deflowering a princess."},
  {text: "Deflowering the princess."},
  {text: "Dorito breath."},
  {text: "Eating an albino."},
  {text: "Enormous Scandinavian women."},
  {text: "Fabricating statistics."},
  {text: "Finding a skeleton."},
  {text: "Gandalf."},
  {text: "Genetically engineered super-soldiers."},
  {text: "George Clooney’s musk."},
  {text: "Getting abducted by Peter Pan."},
  {text: "Getting in her pants, politely."},
  {text: "Gladiatorial combat."},
  {text: "Good grammar."},
  {text: "having a penis"},
  {text: "Hipsters."},
  {text: "Historical revisionism."},
  {text: "Insatiable bloodlust."},
  {text: "Jafar."},
  {text: "Jean-Claude Van Damme in slow motion."},
  {text: "Jean-Claude Van Damme."},
  {text: "Just the tip."},
  {text: "Leveling up."},
  {text: "Literally eating shit."},
  {text: "Mad hacky-sack skills."},
  {text: "Making the penises kiss."},
  {text: "Media coverage."},
  {text: "Medieval Times® Dinner & Tournament."},
  {text: "Mom."},
  {text: "Moral ambiguity."},
  {text: "My machete."},
  {text: "Neil Patrick Harris."},
  {text: "NOOOOOOOOO!!!"},
  {text: "Nubile slave boys."},
  {text: "Ominous background music."},
  {text: "One thousand Slim Jims."},
  {text: "Overpowering your father."},
  {text: "Panty raids."},
  {text: "Pistol-whipping a hostage."},
  {text: "Quiche."},
  {text: "Quivering jowls."},
  {text: "Revenge fucking."},
  {text: "Ripping into a man’s chest and pulling out his still-beating heart."},
  {text: "Ryan Gosling riding in on a white horse."},
  {text: "Salvia."},
  {text: "Sanding off a man’s nose."},
  {text: "Santa Claus."},
  {text: "Savagely beating a mascot"},
  {text: "Scrotum tickling."},
  {text: "Sexual humiliation."},
  {text: "Sexy Siamese twins."},
  {text: "Shaft."},
  {text: "Slow motion."},
  {text: "Space muffins."},
  {text: "Statistically validated stereotypes."},
  {text: "Stockholm syndrome"},
  {text: "Sudden Poop Explosion Disease."},
  {text: "Suicidal thoughts."},
  {text: "Syphilitic insanity"},
  {text: "The boners of the elderly."},
  {text: "The economy."},
  {text: "The Fanta® girls."},
  {text: "The four arms of Vishnu."},
  {text: "The gulags."},
  {text: "The harsh light of day."},
  {text: "The hiccups."},
  {text: "The ooze"},
  {text: "The shambling corpse of Larry King."},
  {text: "This guy!"},
  {text: "Tripping balls."},
  {text: "Walking in on Dad peeing into Mom’s mouth."},
  {text: "Words, words, words."},
  {text: "Zeus’s sexual appetites."},
  {text: "Content."},
  {text: "Fucking me good and taking me to Red Lobster.®"},
  {text: "Self-identifying as a DJ."},
  {text: "Getting high with mom."},
  {text: "Beyoncé."},
  {text: "Gazpacho."},
  {text: "Discovering that what I really want in life is to kill people and have sex with their corpses."},
  {text: "A man with the head of a goat and the body of a goat."},
  {text: "How good lead paint taste."},
  {text: "Dropping dead in a Sbarro’s bathroom and not being found for 72 hours."},
  {text: "Eating too many Cinnabons and then vomiting and then eating the vomit."},
  {text: "Some of that good dick."},
  {text: "Two shitty kids and a garbage husband."},
  {text: "Pooping in the potty."},
  {text: "Bad emotions I don’t want."},
  {text: "Mixing M&Ms and Skittles like some kind of psychopath."},
  {text: "Fucking my therapist."},
  {text: "The best, deepest quotes from The Dark Knight."},
  {text: "Meatloaf, the man."},
  {text: "Meatloaf, the food."},
  {text: "My huge penis and substantial fortune."},
  {text: "Hot lettuce."},
  {text: "It being too late to stop having sex with a horse."},
  {text: "Becoming the President of the United States."},
  {text: "Microaggressions."},
  {text: "Getting the Dorito crumbs out of my purse."},
  {text: "The sweet, forbidden meat of the monkey."},
  {text: "Consensual, nonreproductive incest."},
  {text: "Grunting for ten minutes and then peeing sand."},
  {text: "Prematurely ejaculating like a total loser."},
  {text: "Jazz."},
  {text: "Straight blazin’ 24/7."},
  {text: "Having sex with a beautiful person."},
  {text: "Going around pulling people’s tampons out."},
  {text: "Reaching an age where barbecue chips are better than sex."},
  {text: "Daddy going away forever."},
  {text: "Three hours of nonstop penetration."},
  {text: "Holding the proper political beliefs of my time to attract a mate."},
  {text: "Scissoring, if that’s a thing."},
  {text: "Creamy slices of real, California avocado."},
  {text: "ISIS."},
  {text: "A weird guy who says weird stuff and weirds me out."},
  {text: "Rubbing my bush all over your bald head."},
  {text: "Farting all over my face with your tight little asshole."},
  {text: "Quinoa."},
  {text: "How sad it will be when Morgan Freeman dies."},
  {text: "A cheerfulness that belies a deep-seated self-loathing."},
  {text: "Farting a huge shit out of my pussy."},
  {text: "Defeating a gorilla in single combat."},
  {text: "A big ol’ plate of fettuccine alfredo."},
  {text: "Brunch."},
  {text: "Anal."},
  {text: "A women’s perspective."},
  {text: "A long business meeting with no obvious purpose."},
  {text: "Thinking about what eating even is."},
  {text: "Doing a somersault and barfing."},
  {text: "Trees."},
  {text: "Hating Jews."},
  {text: "Whooping your ass at Mario Kart."},
  {text: "A massive collection of child pornography."},
  {text: "Systems and policies designed to preserve centuries-old power structures."},
  {text: "Having an awesome time drinking and driving."},
  {text: "Muchin’ puss."},
  {text: "Moon people."},
  {text: "Picking up a glass of water and taking a sip and being the president."},
  {text: "Critical thinking."},
  {text: "Showing all the boys my pussy."},
  {text: "Homework."},
  {text: "China."},
  {text: "Putting more black people in jail."},
  {text: "The ol’ penis-in-the-popcorn surprise."},
  {text: "One of them big-city Jew lawyers."},
  {text: "Informing you that I am a registered sex offender."},
  {text: "Rolling so hard."},
  {text: "Who really did 9/11."},
  {text: "Being turned into sausages."},
  {text: "Eating ass."},
  {text: "A dolphin that learns to talk and becomes the Dead of Harvard Law School."},
  {text: "Gay thoughts."},
  {text: "My dog dying."},
  {text: "Dominating a man by peeing on his eldest son."},
  {text: "Dis bitch."},
  {text: "A strong horse and enough rations for thirty days."},
  {text: "Feminism."},
  {text: "A cold and indifferent universe."},
  {text: "An incurable homosexual."},
  {text: "The amount of baby carrots I can fit up my ass."},
  {text: "Huge big balls full of jizz."},
  {text: "Gregor, my largest son."},
  {text: "Esmeralda, my most beautiful daughter."},
  {text: "Trevor, the world’s greatest boyfriend."},
  {text: "Jason, the teen mayor."},
  {text: "That bitch, Stacy."},
  {text: "Gayle from HR."},
  {text: "Gary."},
  {text: "Just now finding out about the Armenian Genocide."},
  {text: "Opening your mouth to talk and a big penis fops out."},
  {text: "Twisting my cock and balls into a balloon poodle."},
  {text: "The wind."},
  {text: "A gun that shoots cobras."},
  {text: "Out-of-control teenage blowjob parties."},
  {text: "A black friend."},
  {text: "The body of a 46-year-old man."},
  {text: "Art."},
  {text: "Water."},
  {text: "Doritos and a Fruit Roll-Up."},
  {text: "Sucking each other’s penises for hours on end."},
  {text: "10,000 shrieking teenage girls."},
  {text: "Whomsoever let the dogs out."},
  {text: "The chicken from Popeyes. ®"},
  {text: "Assassinating the president."},
  {text: "Having sex with a man and then eating his head."},
  {text: "A burrito that’s just sour cream."},
  {text: "An arrangement wherein I give a person money they have sex with me."},
  {text: "Facilitating dialogue and deconstructing binaries."},
  {text: "Taking the form of a falcon."},
  {text: "Watching you die."},
  {text: "An X-Man whose power is that he has sex with dogs and children."},
  {text: "Loud, scary thunder."},
  {text: "Every man’s ultimate fantasy: a perfectly cylindrical vagina."},
  {text: "Tiny, rancid girl farts."},
  {text: "Math."},
  {text: "Founding a major world religion."},
  {text: "Plowing that ass like a New England corn farmer."},
  {text: "Period poops."},
  {text: "The feeling of going to McDonald’s as a 6-year-old."},
  {text: "Misogyny."},
  {text: "Tables."},
  {text: "Feeling the emotion of anger."},
  {text: "One of those “blow jobs” I’ve been hearing so much about."},
  {text: "A creepy child singing a nursery rhyme."},
  {text: "Blossoming into a beautiful young woman."},
  {text: "The secret to truly resilient hair."},
  {text: "Rock-hard tits and a huge vagina."},
  {text: "The lived experience of African Americans."},
  {text: "Mental illness."},
  {text: "Getting eaten out by a dog."},
  {text: "10 football players with erections barreling towards you at full speed."},
  {text: "Starting a shitty podcast."},
  {text: "Overthrowing the democratically-elected government of Chile."},
  {text: "Guns."},
  {text: "A hug."},
  {text: "Getting aborted."},
  {text: "Crazy anal orgasms."},
  {text: "Getting this party started!"},
  {text: "Being sexually attracted to children."},
  {text: "Antidepressants."},
  {text: "Getting trapped in a conversation about Ayn Rand."},
  {text: "Swearing praise upon the Sultan’s hideous daughters."},
  {text: "Turning 32."},
  {text: "Sudden and unwanted slam poetry."},
  {text: "A negative body image that is totally justified."},
  {text: "Exploring each other’s buttholes."},
  {text: "You."},
  {text: "Quacking like a duck in lieu of a cogent argument."},
  {text: "Catching a live salmon in your mouth."},
  {text: "Eating people."},
  {text: "Our baby."},
  {text: "Breastfeeding in public like a radiant earth goddess."},
  {text: "Big, smart money boys tap-tapping on their keyboards."},
  {text: "Finding a nice elevator to poop in."},
  {text: "The mysterious fog rolling into town."},
  {text: "Two beautiful pig sisters."},
  {text: "Condoleezza Rice."},
  {text: "The full force of the American military."},
  {text: "A woman’s right to choose."},
  {text: "A terrified fat child who won’t come out of the bushes."},
  {text: "A medium horchata."},
  {text: "How great my ass looks in these jeans."},
  {text: "Raising three kids on minimum wage."},
  {text: "The bond between a woman and her horse."},
  {text: "Slamming a dunk."},
  {text: "Chris Hemsworth."},
  {text: "Ejaculating at the apex of a cartwheel."},
  {text: "Child labor."},
  {text: "An older man."},
  {text: "Crushing the patriarchy."},
  {text: "Denying the Holocaust."},
  {text: "Falling into a pit of waffles."},
  {text: "Objectifying women."},
  {text: "Everything."},
  {text: "A creature made of penises that must constantly arouse itself to survive."},
  {text: "Getting blasted in the face by a t-shirt cannon."},
  {text: "Onions."},
  {text: "Dumpster juice."},
  {text: "Forty-five minutes of finger blasting."},
  {text: "Film roles for actresses over 40."},
  {text: "Having sex with your mom."},
  {text: "Having a vagina."},
  {text: "Regurgitating a half-digested sparrow."},
  {text: "The hottest MILF in Dallas."},
  {text: "Some real spicy shrimps."},
  {text: "The Rwandan Genocide."},
  {text: "The LGBT community."},
  {text: "Twenty bucks."},
  {text: "The full blown marginalization of ugly people."},
  {text: "A finger up the butt."},
  {text: "A big, beautiful mouth packed to the brim with sparkling teeth."},
  {text: "Getting laid like all the time."},
  {text: "Happy daddies with happy sandals."},
  {text: "Libertarians."},
  {text: "Late-stage dementia."},
  {text: "How strange it is to be anything at all."},
  {text: "Pooping in a leotard and hoping no one notices."},
  {text: "Restoring Germany to its former glory."},
  {text: "Participating."},
  {text: "Going to bed at a reasonable hour."},
  {text: "Smashing my balls at the moment of climax."},
  {text: "Making out and stuff."},
  {text: "Menopause."},
  {text: "The government."},
  {text: "The graceful path of an autumn leaf as it falls to its earthen cradle."},
  {text: "Tender chunks of all-white-meat chicken."},
  {text: "Twenty cheerleaders laughing at your tiny penis."},
  {text: "Mommy and daddy fighting all the time."},
  {text: "Playing my asshole like a trumpet."},
  {text: "Getting naked too soon."},
  {text: "A slowly encroaching circle of wolves."},
  {text: "A man in a suit with perfect hair who tells you beautiful lies."},
  {text: "Seizing control of the means of production."},
  {text: "Comprehensive immigration reform."},
  {text: "Awesome pictures of planets and stuff."},
  {text: "Aborting the shit out of a fetus."},
  {text: "A genetic predisposition for alcoholism."},
  {text: "The flaming wreckage of the International Space Station."},
  {text: "Waking up inside of a tornado."},
  {text: "When the big truck goes “Toot! Toot!”"},
  {text: "The fear and hatred in men’s hearts."},
  {text: "Getting killed and dragged up a tree by a leopard."},
  {text: "Eternal screaming madness."},
  {text: "My brother’s hot friends."},
  {text: "Salsa Night at Dave’s Cantina."},
  {text: "The clown that followed me home from the grocery store."},
  {text: "Watching a hot person eat."},
  {text: "Pretending to be one of the guys but actually being the spider god."},
  {text: "Getting pegged."},
  {text: "An empowered woman."},
  {text: "An old dog full of tumors."},
  {text: "A duffel bag full of lizards."},
  {text: "All these people I’ve killed."},
  {text: "Working so hard to have muscles and then having them."},
  {text: "Political correctness."},
  {text: "A tiny fireman who puts out tiny fires."},
  {text: "Albert Einstein but if he had a huge muscles and a rhinoceros cock."},
  {text: "Chipotle."},
  {text: "A bass drop so huge it tears the starry vault asunder to reveal the face of God."},
  {text: "Growing up chained to a radiator in perpetual darkness."},
  {text: "Shitting all over the floor like a bad, bad girl."},
  {text: "A buttload of candy."},
  {text: "Sucking all the milk out of a yak."},
  {text: "Bullets."},
  {text: "A man who is so cool that he rides on a motorcycle."},
  {text: "Sudden penis loss."},
  {text: "Getting all offended."},
  {text: "Crying and shitting and eating spaghetti."},
  {text: "One unforgettable night of passion."},
  {text: "Being popular and good at sports."},
  {text: "Filling a man’s anus with concrete."},
  {text: "Two whales fucking the shit out of each other."},
  {text: "Cool, relatable cancer teens."},
  {text: "The amount of gay I am."},
  {text: "A possible Muslim."},
  {text: "Unsheathing my massive horse cock."},
  {text: "A bowl of gourds."},
  {text: "The male gaze."},
  {text: "The power of the Dark Side."},
  {text: "Ripping a dog in half."},
  {text: "A constant need for validation."},
  {text: "Meaningless sex."},
  {text: "Such a big boy."},
  {text: "Throwing stones at a man until he dies."},
  {text: "Cancer."},
  {text: "Like a million alligators."},
  {text: "Eating together like a god damn family for once."},
  {text: "Cute boys."},
  {text: "Pussy."},
  {text: "Being a terrible mother."},
  {text: "Never having sex again."},
  {text: "A pizza guy who fucked up."},
  {text: "A whole lotta woman."},
  {text: "The all-new Nissan Pathfinder with 0.9% APR financing!"},
  {text: "A peyote-fueled vision quest."},
  {text: "Kale."},
  {text: "Breastfeeding a ten year old."},
  {text: "Crippling social anxiety."},
  {text: "Immortality cream."},
  {text: "Texas."},
  {text: "Teaching a girl how to handjob the penis."},
  {text: "A turd."},
  {text: "Shapes and colors."},
  {text: "Whatever you wish, mother."},
  {text: "The haunting stare of an Iraqi child."},
  {text: "Robots who just want to party."},
  {text: "A self-microwaving burrito."},
  {text: "Forgetting grandma’s first name."},
  {text: "Our new Buffalo Chicken Dippers®!"},
  {text: "Treasures beyond your wildest dreams."},
  {text: "Getting shot out of a cannon."},
  {text: "The sweet song of sword against sword and the braying of mighty war beasts."},
  {text: "Walking into a glass door."},
  {text: "The color “puce.”"},
  {text: "Every ounce of charisma left in Mick Jagger’s tired body."},
  {text: "The eighth graders."},
  {text: "Setting my balls on fire and cartwheeling to Ohio."},
  {text: "The dentist."},
  {text: "Gwyneth Paltrow’s opinions."},
  {text: "Turning the rivers red with the blood of infidels."},
  {text: "Rabies."},
  {text: "Important news about Taylor Swift."},
  {text: "Ejaculating inside another man’s wife."},
  {text: "Owls, the perfect predator."},
  {text: "Being John Malkovich."},
  {text: "Bathing in moonsblood and dancing around the ancient oak."},
  {text: "An oppressed people with a vibrant culture."},
  {text: "An overwhelming variety of cheeses."},
  {text: "Reading the entire End-User License Agreement."},
  {text: "Morpheus."},
  {text: "Peeing into a girl’s butt to make a baby."},
  {text: "Generally having no idea what’s going on."},
  {text: "No longer finding any Cards Against Humanity card funny."},
  {text: "Used knickers."},
  {text: "The bloody Welsh."},
  {text: "Blowing up Parliament."},
  {text: "A Chealsea smile."},
  {text: "Waking up half-naked in a Little Chef car park."},
  {text: "Badger culling."},
  {text: "The sudden appearance of the Go Compare man."},
  {text: "Women in yoghurt adverts."},
  {text: "Pussy Galore."},
  {text: "A ginger’s freckled ballsack."},
  {text: "Some bloody peace and quiet."},
  {text: "Wiping her bum."},
  {text: "Doing a shit in Pudsey Bear’s eyehole."},
  {text: "England"},
  {text: "Madeleine McCann."},
  {text: "A sober Irishman who doesn’t care for potatoes."},
  {text: "An entrenched class system."},
  {text: "The North."},
  {text: "Rubbing Boris Johnson’s belly until he falls asleep."},
  {text: "The Hillsborough Disaster."},
  {text: "Ripping off the Beatles."},
  {text: "Rohypnol."},
  {text: "The end of days."},
  {text: "Jedward."},
  {text: "A bleached arsehole."},
  {text: "A madman who lives in a police box and kidnaps women."},
  {text: "The Scouts."},
  {text: "Getting naked and watching CBeebies."},
  {text: "Ed Balls."},
  {text: "Millwall fans."},
  {text: "Not wearing trousers."},
  {text: "Cheating in the Paralympics."},
  {text: "The Honey Monster."},
  {text: "Anything that comes out of Prince Philip’s mouth."},
  {text: "Queen Elizabeth’s immaculate anus."},
  {text: "The Black Death."},
  {text: "Perfunctory foreplay."},
  {text: "A mad cow."},
  {text: "A fanny fart."},
  {text: "The Stig."},
  {text: "Wanking into a pool of children’s tears."},
  {text: "A posh wank."},
  {text: "Kids with bum cancer."},
  {text: "Haggis."},
  {text: "Jade Goody’s cancerous remains."},
  {text: "Cheeky bum sex."},
  {text: "Jehovah’s Witnesses."},
  {text: "Leaked footage of Kate Middleton’s colonoscopy."},
  {text: "The petty troubles of the landed gentry."},
  {text: "Scousers."},
  {text: "Maureen of Blackpool, Reader’s Wife of the Year 1988."},
  {text: "Bogies."},
  {text: "Blood, toil, tears, and sweat."},
  {text: "Scalping the Milkybar Kid."},
  {text: "Concealing an erection."},
  {text: "An AK-47 assault rifle."},
  {text: "Shipping convicts to Australia."},
  {text: "A foetus."},
  {text: "Ecstasy."},
  {text: "The BNP."},
  {text: "David Cameron."},
  {text: "Just touching David Beckham’s hair."},
  {text: "Extremely tight trousers."},
  {text: "Druids."},
  {text: "Trench foot."},
  {text: "An argument with Richard Dawkins."},
  {text: "The French."},
  {text: "Dirty nappies."},
  {text: "Germans on holiday."},
  {text: "One Direction’s supple, hairless bodies."},
  {text: "Paedophiles."},
  {text: "Daddies® Brown Sauce."},
  {text: "Pronouncing the names of northern Welsh towns."},
  {text: "Getting wed, having a few kids, taking some pictures, retiring to the south of"},
  {text: "France, and dying."},
  {text: "Spaniards."},
  {text: "Gentleman’s Relish."},
  {text: "Slapping a biscuit out of an orphan’s mouth."},
  {text: "Excalibur."},
  {text: "Gary Glitter."},
  {text: "A white van man."},
  {text: "Hurling one’s body down a hill in pursuit of a wheel of cheese."},
  {text: "Shitting out a perfect Cumberland sausage."},
  {text: "The entire cast of Downton Abbey."},
  {text: "Cottaging."},
  {text: "Five litres of Special Brew."},
  {text: "A vindaloo poo."},
  {text: "A bit of slap and tickle."},
  {text: "A thousand Scottish warriors lifting their kilts in unison."},
  {text: "Buckfast Tonic Wine."},
  {text: "Tories."},
  {text: "400 years of colonial atrocities."},
  {text: "Faffing about."},
  {text: "A nice cup of tea."},
  {text: "Mining accidents."},
  {text: "Jimmy Savile."},
  {text: "LYNX® Body Spray."},
  {text: "The way James Bond treats women."},
  {text: "Dogging."},
  {text: "Abstinence."},
  {text: "Goats eating coins."},
  {text: "Inappropriate yelling."},
  {text: "The plot of a Michael Bay movie."},
  {text: "The Red Menace."},
  {text: "Vehicular homicide."},
  {text: "A caress of the inner thigh"},
  {text: "Filling Sean Hannity with helium and watching him float away."},
  {text: "The homosexual lifestyle."},
  {text: "Swag."},
  {text: "A Fleshlight."},
  {text: "Bio-engineered assault turtles with acid breath."},
  {text: "Court-ordered rehab."},
  {text: "Hip hop jewels"},
  {text: "Joe Biden."},
  {text: "Magnets."},
  {text: "Miley Cyrus at 55."},
  {text: "Our first chimpanzee President."},
  {text: "The cool, refreshing taste of Pepsi®."},
  {text: "The morbidly obese."},
  {text: "The pirate’s life."},
  {text: "The wrath of Vladimir Putin."},
  {text: "This year’s mass shooting."},
  {text: "White-man scalps."},
  {text: "(A picture of Sean Connery from the movie Zardoz)"},
  {text: "Masturbating Yoda’s leathery turtle-penis."},
  {text: "A misty room full of glistening egg sacs."},
  {text: "Going too far with science and bad things happening."},
  {text: "Three boobs."},
  {text: "An alternate history where Hitler was gay but he still killed all those people."},
  {text: "A hazmat suit full of farts."},
  {text: "A protagonist with no qualities."},
  {text: "Darmok and Jalad at Tanagra."},
  {text: "Cheerful blowjob robots."},
  {text: "That girl from the Hungry Games."},
  {text: "Cosmic bowling."},
  {text: "The ending of Lost."},
  {text: "Trimming the poop out of Chewbacca’s butt hair."},
  {text: "A planet-devouring space worm named Rachel."},
  {text: "How great of a movie Men in Black was."},
  {text: "Nine seasons of sexual tension with David Duchovny."},
  {text: "Frantically writing equations on a chalkboard."},
  {text: "Vulcan sex-madness."},
  {text: "Funkified aliens from the planet Groovius."},
  {text: "The dystopia we’re living in right now."},
  {text: "Laying thousands of eggs in a man’s colon."},
  {text: "Beep beep boop beep boop."},
  {text: "Mild amusement"},
  {text: "Casual dismissiveness."},
  {text: "A gnawing sense of dread."},
  {text: "Rage."},
  {text: "Desperately hurling insults at Donald Trump as he absorbs them into his rapidly expanding body."},
  {text: "Trying to wake up from this nightmare."},
  {text: "Finding out democracy might not be such a great idea."},
  {text: "President Donald Trump."},
  {text: "Bringing millions of dangerous, low-paying manufacturing jobs back to America."},
  {text: "Whipping lower-class white men into a xenophobic frenzy."},
  {text: "Making Islam illegal."},
  {text: "The purging of the disloyal."},
  {text: "World Wars 3 through 5."},
  {text: "Nuclear winter."},
  {text: "Roaming through a wasteland of windblown trash and deserted highways."},
  {text: "A black-alley abortion from a Mexican cyborg doctor."},
  {text: "A father and son fighting each other over the last scrap of bread."},
  {text: "Burying my only son."},
  {text: "Extra rations for my litter girl."},
  {text: "Drinking urine to survive."},
  {text: "Trying to remember what music was."},
  {text: "A legitimate reason to commit suicide."},
  {text: "A 55-gallon drum of lube."},
  {text: "A bigger, blacker dick."},
  {text: "A Burmese tiger pit."},
  {text: "A dollop of sour cream."},
  {text: "A fortuitous turnip harvest."},
  {text: "A magic hippie love cloud."},
  {text: "A man in yoga pants with a ponytail and feather earrings."},
  {text: "A piñata full of scorpions"},
  {text: "A sad fat dragon with no friends."},
  {text: "A slightly shittier parallel universe."},
  {text: "A sofa that says “I have style, but I like to be comfortable.”"},
  {text: "A soulful rendition of “Ol’ Man River.”"},
  {text: "A squadron of moles wearing aviator goggles."},
  {text: "A sweaty, panting leather daddy."},
  {text: "A sweet spaceship."},
  {text: "All of this blood."},
  {text: "An army of skeletons."},
  {text: "An ether-soaked rag."},
  {text: "An unhinged ferris wheel rolling toward the sea."},
  {text: "Another shot of morphine."},
  {text: "Basic human decency."},
  {text: "Beefin’ over turf."},
  {text: "Being awesome at sex."},
  {text: "Boris the Soviet Love Hammer."},
  {text: "Bullshit."},
  {text: "Catastrophic urethral trauma."},
  {text: "Crushing Mr. Peanut’s brittle body."},
  {text: "Daddy’s belt"},
  {text: "Death by Steven Seagal."},
  {text: "Dennis the Menace."},
  {text: "Dining with cardboard cutouts of the cast of “Friends.”"},
  {text: "Double penetration."},
  {text: "Existing."},
  {text: "Fetal alcohol syndrome."},
  {text: "Finding Waldo."},
  {text: "Fuck Mountain."},
  {text: "Getting hilariously gang-banged by the Blue Man Group."},
  {text: "Grandpa’s ashes."},
  {text: "Graphic violence, adult language, and some sexual content."},
  {text: "Hillary Clinton’s death stare."},
  {text: "Intimacy problems."},
  {text: "Jeff Goldblum."},
  {text: "Living in a trashcan."},
  {text: "Loki, the trickster god."},
  {text: "Making a friend."},
  {text: "Maximal insertion."},
  {text: "Me."},
  {text: "Mild autism."},
  {text: "Mooing."},
  {text: "My first kill."},
  {text: "Nunchuck moves."},
  {text: "Oncoming traffic."},
  {text: "One Ring to rule them all."},
  {text: "Power"},
  {text: "Pretty Pretty Princess Dress-Up Board Game®."},
  {text: "Pumping out a baby every nine months."},
  {text: "Rising from the grave."},
  {text: "Scrotal frostbite."},
  {text: "Some really fucked-up shit."},
  {text: "Special musical guest, Cher."},
  {text: "Spring break!"},
  {text: "Subduing a grizzly bear and making her your wife."},
  {text: "Survivor’s guilt."},
  {text: "Swiftly achieving orgasm."},
  {text: "Taking a man’s eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes."},
  {text: "The black Power Ranger"},
  {text: "The corporations."},
  {text: "The day the birds attacked."},
  {text: "The Google."},
  {text: "The grey nutrient broth that sustains Mitt Romney."},
  {text: "The human body."},
  {text: "The mere concept of Applebee’s®."},
  {text: "The mixing of the races."},
  {text: "The new Radiohead album."},
  {text: "Tiny nipples."},
  {text: "Tongue."},
  {text: "Upgrading homeless people to mobile hotspots."},
  {text: "Weapons-grade plutonium."},
  {text: "Wearing an octopus for a hat."},
  {text: "Whining like a little bitch."},
  {text: "Whipping a disobedient slave."},
  {text: "That ass."},
  {text: "Nothing."},
  {text: "Shutting the fuck up."},
  {text: "The primal, ball-slapping sex your parents are having right now."},
  {text: "A cat video so cute that your eyes roll back and your spine slides out of your anus."},
  {text: "Cock."},
  {text: "A cop who is also a dog."},
  {text: "Dying alone and in pain."},
  {text: "Gay aliens."},
  {text: "The way white people is."},
  {text: "Reverse cowgirl."},
  {text: "The Quesadilla Explosion Salad from Chili’s."},
  {text: "Actually getting shot, for real."},
  {text: "Not having sex."},
  {text: "Vietnam flashbacks."},
  {text: "Running naked through a mall, pissing and shitting everywhere."},
  {text: "Warm, velvety muppet sex."},
  {text: "Self-flagellation."},
  {text: "The systematic destruction of an entire people and their way of life."},
  {text: "Samuel L. Jackson."},
  {text: "A boo-boo."},
  {text: "Going around punching people."},
  {text: "The entire Internet."},
  {text: "Some kind of bird-man."},
  {text: "Chugging a lava lamp."},
  {text: "Having sex on top of a pizza."},
  {text: "Indescribable loneliness."},
  {text: "An ass disaster."},
  {text: "All my friends dying."},
  {text: "Putting an entire peanut buter and jelly sandwich into the VCR."},
  {text: "Spending lots of money."},
  {text: "Some douche with an acoustic guitar."},
  {text: "Flying robots that kill people."},
  {text: "A greased-up Matthew McConaughey."},
  {text: "An unstoppable wave of fire ants."},
  {text: "Not contributing to society in any meaningful way."},
  {text: "An all-midget production of Shakespeare’s Richard III."},
  {text: "Screaming like a maniac."},
  {text: "The moist, demanding chasm of his mouth."},
  {text: "Filling every orifice with butterscotch pudding."},
  {text: "Unlimited soup, salad, and breadsticks."},
  {text: "Crying into the pages of Sylvia Plath."},
  {text: "Velcro."},
  {text: "A PowerPoint presentation."},
  {text: "A surprising amount of hair."},
  {text: "Eating Tom Selleck’s mustache to gain his powers."},
  {text: "Roland the Farter, flatulist to the king."},
  {text: "A pile of squirming bodies."},
  {text: "Buying the right pants to be cool."},
  {text: "Blood farts."},
  {text: "Three months in the hole."},
  {text: "A botched circumcision."},
  {text: "The Land of Chocolate."},
  {text: "Slapping a racist old lady."},
  {text: "A lamprey swimming up the toilet and latching onto your taint."},
  {text: "Jumping out at people."},
  {text: "A black male in his early 20s, last seen wearing a hoodie."},
  {text: "Mufasa’s death scene."},
  {text: "Bill Clinton, naked on a bearskin rug with a saxophone."},
  {text: "Demonic possession."},
  {text: "The Harlem Globetrotters."},
  {text: "Vomiting mid-blowjob."},
  {text: "My manservant, Claude."},
  {text: "Having shotguns for legs."},
  {text: "Letting everyone down."},
  {text: "A spontaneous conga line."},
  {text: "A vagina that leads to another dimension."},
  {text: "Disco fever."},
  {text: "Getting your dick stuck in a Chinese finger trap with another dick."},
  {text: "Fisting."},
  {text: "The thin veneer of situational causality that underlies porn."},
  {text: "Girls that always be textin’."},
  {text: "Blowing some dudes in an alley."},
  {text: "Drinking ten 5-hour ENERGYs to get fifty continuous hours of energy."},
  {text: "Sneezing, farting, and coming at the same time."},
  {text: "A bunch of idiots playing a card game instead of interacting like normal humans."},
  {text: "A sex goblin with a carnival penis."},
  {text: "Lots and lots of abortions."},
  {text: "Injecting speed into one arm and horse tranquilizer into the other."},
  {text: "Sharks with legs."},
  {text: "A sex comet from Neptune that plunges the Earth into eternal sexiness."},
  {text: "How awesome I am."},
  {text: "Smoking crack, for instance."},
  {text: "A dance move that’s just sex."},
  {text: "A hopeless amount of spiders."},
  {text: "Drinking responsibly."},
  {text: "Angelheaded hipsters burning for the ancient heavenly connection to the starry dynamo in the machinery of the night."},
  {text: "Bouncing up and down."},
  {text: "A shiny rock that proves I love you."},
  {text: "Crazy opium eyes."},
  {text: "Moderate-to-severe joint pain."},
  {text: "Finally finishing off the Indians."},
  {text: "Actual mutants with medical conditions and no superpowers."},
  {text: "The complex geopolitical quagmire that is the Middle East."},
  {text: "Neil Diamond’s Greatest Hits."},
  {text: "No clothes on, penis in vagina."},
  {text: "Whispering all sexy."},
  {text: "A horse with no legs."},
  {text: "Depression."},
  {text: "Almost giving money to a homeless person."},
  {text: "Interspecies marriage."},
  {text: "Blackula."},
  {text: "What Jesus would do."},
  {text: "A manhole."},
  {text: "My dad’s dumb fucking face."},
  {text: "A Ugandan warlord."},
  {text: "My worthless son."},
  {text: "A Native American who solves crimes by going into the spirit world."},
  {text: "A kiss on the lips."},
  {text: "A fart."},
  {text: "The peaceful and nonthreatening rise of China."},
  {text: "Snorting coke off a clown’s boner."},
  {text: "Three consecutive seconds of happiness."},
  {text: "Falling into the toilet."},
  {text: "Ass to mouth."},
  {text: "Some sort of Asian."},
  {text: "The size of my penis."},
  {text: "The safe word."},
  {text: "Party Mexicans."},
  {text: "Ambiguous sarcasm."},
  {text: "Jizz."},
  {text: "An interracial handshake."},
  {text: "10 Incredible Facts About the Anus."},
  {text: "The secret formula for ultimate female satisfaction."},
  {text: "Sugar madness."},
  {text: "Calculating every mannerism so as not to suggest homosexuality."},
  {text: "Fucking a corpse back to life."},
  {text: "All the single ladies."},
  {text: "Whatever a McRib is made of."},
  {text: "Africa."},
  {text: "The euphoric rush of strangling a drifter."},
  {text: "Khakis."},
  {text: "A gender identity that can only be conveyed through slam poetry."},
  {text: "Stuffing a child’s face with Fun Dip until he starts having fun."},
  {text: "A for-real lizard that spits blood from its eyes."},
  {text: "The tiniest shred of evidence that God is real."},
  {text: "Prince Ali, fabulous he, Ali Ababwa."},
  {text: "Dem titties."},
  {text: "Exploding pigeons."},
  {text: "My sex dungeon."},
  {text: "Child Protective Services."},
  {text: "Doo-doo."},
  {text: "Sports."},
  {text: "Unquestioning obedience."},
  {text: "Grammar nazis who are also regular Nazis."},
  {text: "40 acres and a mule."},
  {text: "A crazy little thing called love."},
  {text: "A disappointing salad."},
  {text: "A face full of horse cum."},
  {text: "A giant powdery manbaby."},
  {text: "A mouthful of potato salad."},
  {text: "A one-way ticket to Gary, Indiana."},
  {text: "A powered exoskeleton."},
  {text: "A reason not to commit suicide."},
  {text: "A team of lawyers."},
  {text: "A whole new kind of porn."},
  {text: "A zero-risk way to make $2,000 from home."},
  {text: "AIDS monkeys."},
  {text: "All these decorative pillows."},
  {text: "An unforgettable quinceañera."},
  {text: "An uninterrupted history of imperialism and exploitation."},
  {text: "Anal fissures like you wouldn’t believe."},
  {text: "Ancient Athenian boy-fucking."},
  {text: "Backwards knees."},
  {text: "Being nine years old."},
  {text: "Being paralyzed from the neck down."},
  {text: "Being worshiped as the one true God."},
  {text: "Blackface."},
  {text: "Blowjobs for everyone."},
  {text: "Boring Vaginal sex."},
  {text: "Butt stuff."},
  {text: "Changing a person’s mind with logic and facts."},
  {text: "Child support payments."},
  {text: "Cutting off a flamingo’s legs with garden shears."},
  {text: "Daddy’s credit card."},
  {text: "Deez nuts."},
  {text: "Denzel."},
  {text: "Doing the right stuff to her nipples."},
  {text: "Ejaculating live bees and the bees are angry."},
  {text: "Ennui."},
  {text: "Figuring out how to have sex with a dolphin."},
  {text: "Free ice cream, yo."},
  {text: "Genghis Khan’s DNA."},
  {text: "Getting caught by the police and going to jail."},
  {text: "Getting drive-by shot."},
  {text: "Getting eaten alive by Guy Fieri."},
  {text: "Giant sperm from outer space."},
  {text: "Going to a high school reunion on ketamine."},
  {text: "Having been dead a while."},
  {text: "Mom’s new boyfriend."},
  {text: "My boyfriends stupid penis."},
  {text: "My dead son’s baseball glove."},
  {text: "My first period."},
  {text: "Not believing in giraffes."},
  {text: "Oil!"},
  {text: "Out-of-this-world bazongas."},
  {text: "P.F. Chang himself."},
  {text: "Russian super-tuberculosis."},
  {text: "Seeing my village burned and my family slaughtered before my eyes."},
  {text: "Seeing things from Hitler’s perspective."},
  {text: "September 11th, 2001."},
  {text: "Slowly easing down onto a cucumber."},
  {text: "Social justice warriors with flamethrowers of compassion."},
  {text: "Some shit-hot guitar licks."},
  {text: "The Abercrombie & Fitch lifestyle."},
  {text: "The basic suffering that pervades all of existence."},
  {text: "The eight gay warlocks who dictate the rules of fashion."},
  {text: "The ghost of Marlon Brando."},
  {text: "The inability to form meaningful relationships."},
  {text: "The passage of time."},
  {text: "The swim team, all at once."},
  {text: "The tiger that killed my father."},
  {text: "The unbelievable world of mushrooms."},
  {text: "The black half of Barack Obama."},
  {text: "The white half of Barack Obama."},
  {text: "Too much cocaine."},
  {text: "Unrelenting genital punishment."},
  {text: "Vegetarian options."},
  {text: "Wearing glasses and sounding smart."},
  {text: "Western standards of beauty."},
  {text: "Coronavirus."},
  {text: "COVID-19."},
  {text: "Two midgets shitting into a bucket."}
])

User.create([
  {email: 'test1@test.com', password: 'test1234', password_confirmation: 'test1234', created_at: '2020-04-10 20:59:51.768682', updated_at: '2020-04-10 20:59:51.768682'},
  {email: 'test2@test.com', password: '1234test', password_confirmation: '1234test', created_at: '2020-04-10 20:59:51.768682', updated_at: '2020-04-10 20:59:51.768682'}
])

BlackCard.create([
  {text: "Introducing X-treme Baseball! It’s like baseball, but with __________!", pick_amount: "1"},
  {text: "That’s right, I killed _________________. How, you ask? _________________.", pick_amount: "2"},
  {text: "How did I lose my virginity?", pick_amount: "1"},
  {text: "Kids, I don’t need drugs to get high. I’m high on __________.", pick_amount: "1"},
  {text: "What’s my secret power?", pick_amount: "1"},
  {text: "Just once, I’d like to hear you say “Thanks, Mom. Thanks for _________________.”", pick_amount: "1"},
  {text: "My fellow Americans: Before this decade is out, we will have __________________ on the moon!", pick_amount: "1"},
  {text: "What’s Teach For America using to inspire inner city students to succeed?", pick_amount: "1"},
  {text: "__________________ is a slippery slope that leads to _________________.", pick_amount: "2"},
  {text: "Fun tip! When your man asks you to go down on him, try surprising him with __________________ instead.", pick_amount: "1"},
  {text: "In M. Night Shyamalan’s new movie, Bruce Willis discovers that __________had really been _______________ all along.", pick_amount: "2"},
  {text: "IF you like __________________, YOU MIGHT BE A REDNECK.", pick_amount: "1"},
  {text: "I got 99 problems but _______________ ain’t one.", pick_amount: "1"},
  {text: "What’s that sound?", pick_amount: "1"},
  {text: "What’s there a ton of in heaven?", pick_amount: "1"},
  {text: "Lifetime® presents “_________________: the Story of _________________.”", pick_amount: "2"},
  {text: "After eight years in the White House, how is Obama finally letting loose?", pick_amount: "1"},
  {text: "But before I kill you, Mr. Bond, I must show you __________________.", pick_amount: "1"},
  {text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________________.", pick_amount: "1"},
  {text: "Hey Reddit! I’m __________________. Ask me anything.", pick_amount: "1"},
  {text: "Next from J.K. Rowling: Harry Potter and the Chamber of __________________.", pick_amount: "1"},
  {text: "Dude, do not go in that bathroom. There’s __________ in there.", pick_amount: "1"},
  {text: "_________________.  Betcha can’t have just one!", pick_amount: "1"},
  {text: "In the Disney Channel Original Movie, Hannah Montana struggles with _____________ for the first time.", pick_amount: "1"},
  {text: "When Pharaoh remained unmoved, Moses called down a Plague of __________________.", pick_amount: "1"},
  {text: "50% of all marriages end in __________________.", pick_amount: "1"},
  {text: "Life for American Indians was forever changed when the White Man introduced them to __________________.", pick_amount: "1"},
  {text: "White people like __________________.", pick_amount: "1"},
  {text: "Just saw this upsetting video! Please retweet!! #stop_____________", pick_amount: "1"},
  {text: "Dear Abby, I’m having some trouble with __________________ and would like your advice.", pick_amount: "1"},
  {text: "What never fails to liven up the party?", pick_amount: "1"},
  {text: "Hey guys, welcome to Chili’s! Would you like to start the night off right with _________________?", pick_amount: "1"},
  {text: "What would grandma find disturbing, yet oddly charming?", pick_amount: "1"},
  {text: "What ended my last relationship?", pick_amount: "1"},
  {text: "I’m no doctor but I’m pretty sure what you’re suffering from is called “__________.”", pick_amount: "1"},
  {text: "They said we were crazy. They said we couldn’t put __________________ inside of _________. They were wrong.", pick_amount: "2"},
  {text: "What’s that smell?", pick_amount: "1"},
  {text: "Here is the church Here is the steeple Open the doors And there is __________________.", pick_amount: "1"},
  {text: "Next on ESPN2: The World Series of __________________.", pick_amount: "1"},
  {text: "What is Batman’s guilty pleasure.", pick_amount: "1"},
  {text: "I’m sorry, Professor, but I couldn’t complete my homework because of __________.", pick_amount: "1"},
  {text: "It’s a pity that kids these days are all getting involved with _____________.", pick_amount: "1"},
  {text: "For my next trick, I will pull __________ out of ___________.", pick_amount: "2"},
  {text: "I’m going on a cleanse this week. Nothing but kale juice and __________________.", pick_amount: "1"},
  {text: "Daddy, why is mommy crying?", pick_amount: "1"},
  {text: "This season at Steppenwolf, Samuel Beckett’s classic existential play: Waiting for __________________.", pick_amount: "1"},
  {text: " __________________, Mabe she’s born with it.", pick_amount: "1"},
  {text: "Maybe it’s __________________.", pick_amount: "1"},
  {text: "Why do I hurt all over?", pick_amount: "1"},
  {text: "The class field trip was completely ruined by __________________.", pick_amount: "1"},
  {text: "When I am President,", pick_amount: "1"},
  {text: "I will create the Department of __________________.", pick_amount: "1"},
  {text: "Make a haiku.", pick_amount: "3"},
  {text: "__________________, It’s a trap!", pick_amount: "1"},
  {text: "I never truly understood __________________ until I encountered _________________.", pick_amount: "2"},
  {text: "Uh, hey guys, I know this was my idea, but I’m having serious doubts about ____________., pick_amount: 1"},
  {text: "After four platinum albums and three Grammys, it’s time to get back to my roots, to what inspired me to make music in the first place: __________.", pick_amount: "1"},
  {text: "__________________: kid-tested, mother-approved.", pick_amount: "1"},
  {text: "This is the way the world ends This is the way the world ends Not with a bang but with __________________.", pick_amount: "1"},
  {text: "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ___________________.", pick_amount: "1"},
  {text: "Military historians remember Alexander the Great for his brilliant use of ____________________ against the Persians.", pick_amount: "1"},
  {text: "TSA guidelines now prohibit __________________ on airplanes.", pick_amount: "1"},
  {text: "And the Academy Award for __________________ goes to __________.", pick_amount: "2"},
  {text: "Step 1: __________. Step 2: __________. Step 3: Profit.", pick_amount: "2"},
  {text: "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _____________________.", pick_amount: "1"},
  {text: "________ + ________ = ________________.", pick_amount: "3"},
  {text: "When I was tripping on acid, __________________ turned into _________________.", pick_amount: "2"},
  {text: "Instead of coal, Santa now gives the bad children __________________.", pick_amount: "1"},
  {text: "What is George W. Bush thinking about right now?", pick_amount: "1"},
  {text: "A romantic, candlelit dinner would be incomplete without __________________.", pick_amount: "1"},
  {text: "What’s a girl’s best friend?", pick_amount: "1"},
  {text: "What are my parents hiding from me?", pick_amount: "1"},
  {text: "What made my first kiss so awkward?", pick_amount: "1"},
  {text: "Bravo’s new reality show features eight washed-up celebrities living with _____________.", pick_amount: "1"},
  {text: "During sex, I like to think about __________________.", pick_amount: "1"},
  {text: "Why am I sticky?", pick_amount: "1"},
  {text: "What will always get you laid?", pick_amount: "1"},
  {text: "Why can’t I sleep at night?", pick_amount: "1"},
  {text: "Coming to Broadway this season, __________________: The Musical.", pick_amount: "1"},
  {text: "Introducing the amazing superhero/sidekick duo! It’s __________ and _____________!", pick_amount: "2"},
  {text: "War! What is it good for?", pick_amount: "1"},
  {text: "An international tribunal has found ______ guilty of ______.", pick_amount: "2"},
  {text: "And I would have gotten away with it, too, if it hadn’t been for ______!", pick_amount: "1"},
  {text: "Dear Sir or Madam, We regret to inform you that the Office of ______ has denied your request for ______.", pick_amount: "2"},
  {text: "He who controls ______ controls the world.", pick_amount: "1"},
  {text: "I learned the hard way that you can’t cheer up a grieving friend with ______.", pick_amount: "1"},
  {text: "In a pinch, ______ can be a suitable substitute for ______.", pick_amount: "2"},
  {text: "In his new self-produced album, Kanye West raps over the sounds of ______.", pick_amount: "1"},
  {text: "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated ______.", pick_amount: "1"},
  {text: "In Rome, there are whisperings that the Vatican has a secret room devoted to ______.", pick_amount: "1"},
  {text: "In the distant future, historians will agree that ______ marked the beginning of America’s decline.", pick_amount: "1"},
  {text: "Michael Bay’s new three-hour action epic pits ______ against ______.", pick_amount: "2"},
  {text: "My plan for world domination begins with ______.", pick_amount: "1"},
  {text: "Next season on Man vs, Wild, Bear Grylls must survive the depths of the Amazon with only ______ and his wits.", pick_amount: "1"},
  {text: "Science will never explain ______.", pick_amount: "1"},
  {text: "Science will never explain the origin of ______.", pick_amount: "1"},
  {text: "The CIA now interrogates enemy agents by repeatedly subjecting them to ______.", pick_amount: "1"},
  {text: "The secret to a lasting marriage is communication, communication, and ______.", pick_amount: "1"},
  {text: "The socialist governments of Scandinavia have declared that access to ______ is a basic human right.", pick_amount: "1"},
  {text: "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only ______ and his wits.", pick_amount: "1"},
  {text: "What brought the orgy to a grinding halt?", pick_amount: "1"},
  {text: "What has been making life difficult at the nudist colony?", pick_amount: "1"},
  {text: "What’s the gift that keeps on giving?", pick_amount: "1"},
  {text: "When all else fails, I can always masturbate to ______.", pick_amount: "1"},
  {text: "When I pooped, what came out of my butt?", pick_amount: "1"},
  {text: "I may not be much to look at, but I fuck like ___.", pick_amount: "1"},
  {text: "Errbody in the club ___.", pick_amount: "1"},
  {text: "The top Google auto-complete results for “Barack Obama”: Barack Obama Height. Barack Obama net worth. Barack Obama ___.", pick_amount: "1"},
  {text: "Son, take it from someone who’s been around the block a few times. Nothin’ puts her in the mood like ___.", pick_amount: "1"},
  {text: "Art isn’t just a painting in a stuffy museum. Art is alive. Art is ___.", pick_amount: "1"},
  {text: "You won’t believe what’s in my pussy. It’s ___.", pick_amount: "1"},
  {text: "What’s the most problematic?", pick_amount: "1"},
  {text: "Feeling so grateful! #amazing #mylife #___.", pick_amount: "1"},
  {text: "What’s a total waste of Hillary Clinton’s time?", pick_amount: "1"},
  {text: "What’s the gayest?", pick_amount: "1"},
  {text: "___ be all like ___.", pick_amount: "2"},
  {text: "Girls just wanna have ___.", pick_amount: "1"},
  {text: "One more thing. Watch out for Big Mike. They say he killed a man with ___.", pick_amount: "1"},
  {text: "Well, shit. My eyes ain’t so good, but I’ll eat my own boot if that ain’t ___!", pick_amount: "1"},
  {text: "If at first you don’t succeed, try ___.", pick_amount: "1"},
  {text: "What will end racism once and for all?", pick_amount: "1"},
  {text: "I’ll take the BBQ bacon burger with friend egg and fuck it how about ___.", pick_amount: "1"},
  {text: "Well if ___ is a crime, then lock me up!", pick_amount: "1"},
  {text: "We do not shake with our left hands in this country. That is the hand we use for ___.", pick_amount: "1"},
  {text: "You know who else liked ___? Hitler.", pick_amount: "1"},
  {text: "Poor Brandon, still living in his parent’s basement. I heard he never got over ___.", pick_amount: "1"},
  {text: "What totally destroyed my asshole?", pick_amount: "1"},
  {text: "I don’t believe in God. I believe in ___.", pick_amount: "1"},
  {text: "Then the princess kissed the frog, and all of a sudden the frog was ___!", pick_amount: "1"},
  {text: "I got rhythm, I’ve got music, I’ve got ___. Who could ask for anything more?", pick_amount: "1"},
  {text: "No, no, no, no, no, no, NO! I will NOT let ___ ruin this wedding.", pick_amount: "1"},
  {text: "Coming to Red Lobster® this month, ___.", pick_amount: "1"},
  {text: "Ooo, daddy like ___.", pick_amount: "1"},
  {text: "Best you go back where you came from, now. We don’t take too kindly to ___ in these parts.", pick_amount: "1"},
  {text: "Summer lovin’, had me a blast. ___, happened so fast.", pick_amount: "1"},
  {text: "LSD + ___ = really bad time.", pick_amount: "1"},
  {text: "What are all those whales singing about?", pick_amount: "1"},
  {text: "As Teddy Roosevelt said, the four manly virtues are honor, temperance, industry, and ___.", pick_amount: "1"},
  {text: "I tell you, it was a non-stop fuckfest. When it was over, my asshole looked like ___.", pick_amount: "1"},
  {text: "What turned me into a Republican?", pick_amount: "1"},
  {text: "I’m sorry, sir, but your insurance plan doesn’t cover injuries caused by ___.", pick_amount: "1"},
  {text: "Run, run, as fast as you can! You can’t catch me, I’m ___!", pick_amount: "1"},
  {text: "There is no God. It’s just ___ and then you die.", pick_amount: "1"},
  {text: "She’s just one of the guys, you know? She likes beer, and football, and ___.", pick_amount: "1"},
  {text: "This Friday at the Liquid Lunge, it’s ___ Night! Ladies drink free.", pick_amount: "1"},
  {text: "What sucks balls?", pick_amount: "1"},
  {text: "I’ve had a horrible vision, father. I saw mountains crumbling, stars falling from the sky. I saw ___.", pick_amount: "1"},
  {text: "Oh no! Siri, how do I fix ___?", pick_amount: "1"},
  {text: "Dance like there’s nobody watching, love like you’ll never be hurt, and live like you’re ___.", pick_amount: "1"},
  {text: "Mom’s to-do list: Buy Groceries Clean up ___. Soccer Practice.", pick_amount: "1"},
  {text: "Why am I laughing and crying and taking off my clothes?", pick_amount: "1"},
  {text: "She’s a lady in the streets, ___ in the sheets.", pick_amount: "1"},
  {text: "What’s about to take dance floor to the next level?", pick_amount: "1"},
  {text: "CNN breaking news! Scientists discover ___.", pick_amount: "1"},
  {text: "Most Americans would not vote for a candidate who is openly ___.", pick_amount: "1"},
  {text: "Congratulations! You have been selected for our summer internship program. While we are unable to off a salary, we can off you ___.", pick_amount: "1"},
  {text: "In the 1950s, psychologists prescribed ___ as a cure for homosexually.", pick_amount: "1"},
  {text: "As reparations for slavery, all African Americans will receive ___.", pick_amount: "1"},
  {text: "With a one-time gift of just $10, you can save this child from ___.", pick_amount: "1"},
  {text: "Google Calendar alert: ___ in 10 minutes.", pick_amount: "1"},
  {text: "I work my ass off all day for this family, and this what I come home to? _________!?", pick_amount: "1"},
  {text: "I have a strict policy. First date, dinner. Second date, kiss. Third date, _________.", pick_amount: "1"},
  {text: "When I was a kid we used to play Cowboys and _________.", pick_amount: "1"},
  {text: "This is America. If you don’t work hard, you don’t succeed. I don’t care if you’re black, white, purple, or _________.", pick_amount: "1"},
  {text: "You Won’t Believe These 15 Hilarious _________ Bloopers!", pick_amount: "1"},
  {text: "James is a lonely boy. But when he discovers a secret door in his attic, he meets a magical new friend: _________.", pick_amount: "1"},
  {text: "Don’t worry, kid. It gets better. I’ve been living with _________ for 20 years.", pick_amount: "1"},
  {text: "My grandfather worked his way up from nothing.", pick_amount: "1"},
  {text: "When he came to this country, all he had was the shoes on his feet and _________.", pick_amount: "1"},
  {text: "Behind every powerful man is _________.", pick_amount: "1"},
  {text: "You are not alone. Millions of Americans struggle with _________ every day.", pick_amount: "1"},
  {text: "Come to Dubai, where you can relax in our world-famous spas, experience the nightlife, or simply enjoy _________ by the poolside.", pick_amount: "1"},
  {text: "“This is madness!” “No. THIS IS _________!”", pick_amount: "1"},
  {text: "Listen, Gary, I like you. But if you want that corner office, you’re going to have to show me _________.", pick_amount: "1"},
  {text: "I went to the desert and ate of the peyote cactus. Turns out my spirit animal is _________.", pick_amount: "1"},
  {text: "And would you like those buffalo wings mild, hot, or _________?", pick_amount: "1"},
  {text: "The six things I could never do without: oxygen, facebook, chocolate, netflix, friends, and _________ !", pick_amount: "1"},
  {text: "Why won’t you make love to me anymore? Is it _________?", pick_amount: "1"},
  {text: "Puberty is a time of change. You might notice hair growing in new places. You might develop an interest in _________. This is normal.", pick_amount: "1"},
  {text: "I’m sorry, Mrs. Chen, but there was nothing we could do. At 4:15 this morning, your son succumbed to _________.", pick_amount: "1"},
  {text: "I’m Miss Tennessee, and if I could make the world better by changing one thing, I would get rid of _________.", pick_amount: "1"},
  {text: "Tonight, we will have sex. And afterwards, if you’d like, a little bit of _________.", pick_amount: "1"},
  {text: "Everybody join hands and close your eyes. Do you sense that? That’s the presence of _________ in this room.", pick_amount: "1"},
  {text: "To become a true Yanomamo warrior, you must prove that you can withstand _________ without crying out.", pick_amount: "1"},
  {text: "Y’all ready to get this thing started? I’m Nick Cannon, and this is America’s Got _________.", pick_amount: "1"},
  {text: "If you had to describe me, the Card Czar, using only one of the cards in your hand, which one would it be?", pick_amount: "1"},
  {text: "The Natural History Museum has just opened an interactive exhibit on ________.", pick_amount: "1"},
  {text: "Dear Agony Aunt, I’m having some trouble with ________ and I need your advice.", pick_amount: "1"},
  {text: "I’m sorry,Sir, but I couldn’t complete my homework because of ________.", pick_amount: "1"},
  {text: "The theme for next year’s Eurovision Song Contest is “We are ________.”", pick_amount: "1"},
  {text: "Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and ________.", pick_amount: "1"},
  {text: "In Wormwood Scrubs, word is you can trade 200 cigarettes for ________.", pick_amount: "1"},
  {text: "________? Jim’ll fix it!", pick_amount: "1"},
  {text: "When I am Prime Minister of the United Kingdom, I will create the Ministry of ________.", pick_amount: "1"},
  {text: "What kept Margaret Thatcher busy in her waning years?", pick_amount: "1"},
  {text: "In her latest feature-length film, Tracy Beaker struggles with ________ for the first time.", pick_amount: "1"},
  {text: "Airport security guidelines now prohibit ________ on airplanes.", pick_amount: "1"},
  {text: "The school field trip was completely ruined by ________.", pick_amount: "1"},
  {text: "What did I bring back from Amsterdam?", pick_amount: "1"},
  {text: "The TFL apologizes for the delay in train service due to ________.", pick_amount: "1"},
  {text: "And the BAFTA for ________ goes to ________.", pick_amount: "2"},
  {text: "Next on Sky Sports: The World Championship of ________.", pick_amount: "1"},
  {text: "Channel 5’s new reality show features eight washed-up celebrities living with ________.", pick_amount: "1"},
  {text: "Instead of coal, Father Christmas now gives bad children ________.", pick_amount: "1"},
  {text: "Coming to the West End this year, ________: The Musical.", pick_amount: "1"},
  {text: "________: Once you pop, the fun don’t stop!", pick_amount: "1"},
  {text: "Channel 4 presents ________, the story of ________.", pick_amount: "2"},
  {text: "What are school administrators using to curb rampant teenage pregnancy?", pick_amount: "1"},
  {text: "________. That’s why mums go to Iceland.", pick_amount: "1"},
  {text: "Daddy, why is mummy crying?", pick_amount: "1"},
  {text: "This ia a vital update from the Government about ________.", pick_amount: "1"}
])
